/* Расширенный банк вопросов грамматики «Лингво»: в каждой теме ещё 12 вопросов
   «выбери форму» (mc), 8 предложений для перевода (tr: русский, эталон, другие
   верные варианты) и 10 заданий «впиши форму» (gap: фраза с ___, подсказка
   в скобках, верный ответ и допустимые варианты). Дописывается к GRAMMAR. */
const GRAMMAR_EXT = {
be: {
  mc: [["My name ___ Anna.", "is", "are", "am", "be"],
       ["They ___ my friends.", "are", "is", "am", "be"],
       ["I ___ 25 years old.", "am", "is", "are", "have"],
       ["___ he your brother?", "Is", "Are", "Am", "Does"],
       ["The coffee ___ very hot.", "is", "are", "am", "be"],
       ["We ___ not at home now.", "are", "is", "am", "do"],
       ["___ your parents at work?", "Are", "Is", "Am", "Do"],
       ["It ___ cold today.", "is", "are", "am", "has"],
       ["You ___ late again!", "are", "is", "am", "be"],
       ["My sister ___ a nurse.", "is", "are", "am", "has"],
       ["Where ___ the station?", "is", "are", "am", "does"],
       ["Tom and I ___ colleagues.", "are", "is", "am", "be"]],
  tr: [["Мне 30 лет.", "I am 30 years old.", "I am thirty years old.", "I am 30.", "I am thirty."],
       ["Он не дома.", "He is not at home.", "He is not home."],
       ["Они студенты.", "They are students."],
       ["Ты врач?", "Are you a doctor?"],
       ["Сегодня жарко.", "It is hot today.", "Today it is hot."],
       ["Мы не друзья.", "We are not friends."],
       ["Как тебя зовут?", "What is your name?"],
       ["Кофе очень горячий.", "The coffee is very hot."]],
  gap: [["I ___ (be) a student.", "am"],
        ["She ___ (be) from Spain.", "is"],
        ["They ___ (be) at school now.", "are"],
        ["___ (be) you OK?", "Are"],
        ["He ___ (not / be) married.", "is not"],
        ["We ___ (be) very happy.", "are"],
        ["___ (be) it your phone?", "Is"],
        ["The shops ___ (not / be) open on Sunday.", "are not"],
        ["My dog ___ (be) very friendly.", "is"],
        ["I ___ (not / be) ready yet.", "am not"]] },
ps: {
  mc: [["She ___ TV every evening.", "watches", "watch", "watchs", "watching"],
       ["We ___ to work by bus.", "go", "goes", "going", "are go"],
       ["___ he speak French?", "Does", "Do", "Is", "Are"],
       ["I ___ like horror films.", "don't", "doesn't", "not", "am not"],
       ["My brother ___ football on Sundays.", "plays", "play", "playing", "is play"],
       ["The shop ___ at 9 o'clock.", "opens", "open", "opening", "to open"],
       ["Where ___ you live?", "do", "does", "are", "is"],
       ["He never ___ breakfast.", "eats", "eat", "eating", "doesn't eat"],
       ["My cat ___ milk.", "doesn't like", "don't like", "not like", "doesn't likes"],
       ["What time ___ the film start?", "does", "do", "is", "are"],
       ["They usually ___ dinner at home.", "have", "has", "having", "are have"],
       ["She ___ two languages.", "speaks", "speak", "speaking", "is speak"]],
  tr: [["Он играет в футбол по выходным.", "He plays football at the weekend.", "He plays football on weekends.", "He plays football at weekends."],
       ["Я не люблю молоко.", "I don't like milk."],
       ["Она часто читает.", "She often reads."],
       ["Во сколько ты встаёшь?", "What time do you get up?"],
       ["Мой брат не работает.", "My brother doesn't work."],
       ["Они живут в маленьком городе.", "They live in a small town."],
       ["Магазин открывается в девять.", "The shop opens at nine."],
       ["Ты пьёшь кофе?", "Do you drink coffee?"]],
  gap: [["She ___ (work) in a hospital.", "works"],
        ["He ___ (watch) TV every evening.", "watches"],
        ["I ___ (not / eat) meat.", "don't eat"],
        ["___ (you / like) coffee?", "Do you like"],
        ["My dad ___ (go) to work by car.", "goes"],
        ["She ___ (not / speak) Spanish.", "doesn't speak"],
        ["Where ___ (he / live)?", "does he live"],
        ["We often ___ (meet) on Fridays.", "meet"],
        ["The train ___ (leave) at 6.", "leaves"],
        ["My sister ___ (study) at university.", "studies"]] },
there: {
  mc: [["There ___ a cat on the sofa.", "is", "are", "be", "has"],
       ["There ___ two bedrooms in our flat.", "are", "is", "be", "have"],
       ["___ any shops near here?", "Are there", "Is there", "There are", "Have there"],
       ["There ___ a lot of cars today.", "are", "is", "be", "has"],
       ["___ some apples in the bag.", "There are", "There is", "It is", "They is"],
       ["How many people ___ in your family?", "are there", "is there", "there are", "there is"],
       ["There ___ a problem with my phone.", "is", "are", "be", "have"],
       ["There ___ any students in the classroom.", "aren't", "isn't", "don't", "not"],
       ["___ a cash machine in this street?", "Is there", "Are there", "There is", "Has"],
       ["There ___ much time left.", "isn't", "aren't", "don't", "not"],
       ["There ___ three cafes on this street.", "are", "is", "be", "has"],
       ["___ a good film on TV tonight.", "There is", "There are", "It has", "They are"]],
  tr: [["В парке много деревьев.", "There are many trees in the park.", "There are a lot of trees in the park."],
       ["На столе есть книга.", "There is a book on the table."],
       ["Здесь есть туалет?", "Is there a toilet here?"],
       ["В комнате нет окон.", "There aren't any windows in the room.", "There are no windows in the room."],
       ["В моём городе есть музей.", "There is a museum in my town.", "There is a museum in my city."],
       ["Сколько человек в классе?", "How many people are there in the class?"],
       ["В кофе нет сахара.", "There isn't any sugar in the coffee.", "There is no sugar in the coffee."],
       ["Рядом есть аптеки?", "Are there any pharmacies nearby?", "Are there any pharmacies near here?"]],
  gap: [["There ___ (be) a park near my house.", "is"],
        ["There ___ (be) five people in my family.", "are"],
        ["___ (be) there a lift in this building?", "Is"],
        ["There ___ (not / be) any bread.", "isn't"],
        ["___ (be) there any questions?", "Are"],
        ["There ___ (be) a lot of people here today.", "are"],
        ["There ___ (not / be) any chairs in the room.", "aren't"],
        ["How many rooms ___ (be) there?", "are"],
        ["There ___ (be) a mistake in your text.", "is"],
        ["There ___ (be) some milk in the fridge.", "is"]] },
can: {
  mc: [["I ___ play the guitar.", "can", "cans", "can to", "am can"],
       ["___ she drive?", "Can", "Does", "Is", "Do"],
       ["We can ___ tomorrow.", "meet", "to meet", "meeting", "meets"],
       ["He ___ come to the party. He's ill.", "can't", "don't", "isn't", "not can"],
       ["Can you ___ me the salt, please?", "pass", "to pass", "passing", "passes"],
       ["My son ___ read yet.", "can't", "doesn't can", "not can", "isn't"],
       ["___ I open the window?", "Can", "Do", "Am", "Does"],
       ["They can ___ English very well.", "speak", "speaks", "to speak", "speaking"],
       ["I'm sorry, I ___ help you.", "can't", "don't can", "am not can", "not"],
       ["Can he ___ fast?", "run", "runs", "running", "to run"],
       ["You ___ park here. It's free.", "can", "can to", "cans", "are can"],
       ["___ you swim?", "Can", "Are", "Does", "Is"]],
  tr: [["Я умею плавать.", "I can swim."],
       ["Она не может прийти.", "She can't come."],
       ["Можно я сяду здесь?", "Can I sit here?"],
       ["Ты умеешь готовить?", "Can you cook?"],
       ["Мы не можем найти ключи.", "We can't find the keys.", "We can't find our keys."],
       ["Он умеет играть на пианино.", "He can play the piano."],
       ["Можешь говорить медленнее?", "Can you speak more slowly?", "Can you speak slower?"],
       ["Я не умею танцевать.", "I can't dance."]],
  gap: [["She ___ tennis very well. (умеет играть)", "can play"],
        ["I ___ my phone. (не могу найти)", "can't find"],
        ["___ me, please? (можешь помочь)", "Can you help"],
        ["He ___. He's afraid of water. (не умеет плавать)", "can't swim"],
        ["We ___ the sea from our window. (можем видеть)", "can see"],
        ["___ by card? (можно мне заплатить)", "Can I pay"],
        ["My grandmother ___ a smartphone. (не умеет пользоваться)", "can't use"],
        ["You ___ me any time. (можешь звонить)", "can call"],
        ["They ___ today. (не могут прийти)", "can't come"],
        ["___ Chinese? (она умеет говорить)", "Can she speak"]] },
art: {
  mc: [["I need ___ umbrella.", "an", "a", "the", "—"],
       ["___ moon is beautiful tonight.", "The", "A", "An", "—"],
       ["He is ___ honest man.", "an", "a", "the", "—"],
       ["I saw a dog. ___ dog was very big.", "The", "A", "An", "—"],
       ["She speaks ___ English.", "—", "the", "an", "a"],
       ["Can you pass me ___ salt, please?", "the", "a", "an", "—"],
       ["We have ___ new car.", "a", "an", "the", "—"],
       ["I usually have ___ breakfast at 8.", "—", "a", "the", "an"],
       ["He wants to be ___ engineer.", "an", "a", "the", "—"],
       ["What ___ beautiful day!", "a", "the", "an", "—"],
       ["Paris is ___ capital of France.", "the", "a", "an", "—"],
       ["I'll be back in ___ hour.", "an", "a", "the", "—"]],
  tr: [["У меня есть идея.", "I have an idea."],
       ["Он музыкант.", "He is a musician."],
       ["Закрой дверь, пожалуйста.", "Close the door, please.", "Please close the door."],
       ["Луна сегодня большая.", "The moon is big tonight.", "The moon is big today."],
       ["Я хочу апельсин.", "I want an orange."],
       ["Она говорит по-французски.", "She speaks French."],
       ["Ключи на столе.", "The keys are on the table."],
       ["Это интересная книга.", "This is an interesting book.", "It is an interesting book."]],
  gap: [["He works as ___ engineer. (a / an / the)", "an"],
        ["___ Earth goes around the Sun. (a / an / the)", "The"],
        ["I have ___ idea! (a / an / the)", "an"],
        ["She is ___ best student in the class. (a / an / the)", "the"],
        ["Wait ___ minute, please. (a / an / the)", "a"],
        ["My father is ___ architect. (a / an / the)", "an"],
        ["Could you turn off ___ light, please? (a / an / the)", "the"],
        ["It takes ___ hour to get there. (a / an / the)", "an"],
        ["What ___ nice surprise! (a / an / the)", "a"],
        ["London is ___ capital of the UK. (a / an / the)", "the"]] },
pc: {
  mc: [["Be quiet! The baby ___.", "is sleeping", "sleeps", "sleep", "sleeping"],
       ["They ___ football right now.", "are playing", "play", "is playing", "playing"],
       ["___ she working today?", "Is", "Does", "Are", "Do"],
       ["I ___ a book at the moment.", "am reading", "read", "reading", "am read"],
       ["We ___ for the bus.", "are waiting", "wait", "waiting", "are wait"],
       ["Why ___ you laughing?", "are", "do", "is", "does"],
       ["He ___ to music now.", "is listening", "listens", "listen", "listening"],
       ["I ___ what you mean.", "understand", "am understanding", "understanding", "understands"],
       ["Listen! Someone ___ at the door.", "is knocking", "knocks", "knock", "knocking"],
       ["She ___ a red dress today.", "is wearing", "wears", "wear", "wearing"],
       ["We ___ dinner. Can I call you back?", "are having", "have", "has", "having"],
       ["Look! The children ___ in the snow.", "are playing", "is playing", "play", "playing"]],
  tr: [["Я сейчас готовлю ужин.", "I am cooking dinner now.", "I am making dinner now."],
       ["Что ты читаешь?", "What are you reading?"],
       ["Он сейчас спит.", "He is sleeping now."],
       ["Они играют в парке.", "They are playing in the park."],
       ["Ты меня слушаешь?", "Are you listening to me?"],
       ["Она не работает сегодня.", "She isn't working today."],
       ["Мы смотрим фильм.", "We are watching a film.", "We are watching a movie."],
       ["Куда ты идёшь?", "Where are you going?"]],
  gap: [["She ___ (cook) dinner now.", "is cooking"],
        ["I ___ (write) an email at the moment.", "am writing"],
        ["What ___ (you / do)?", "are you doing"],
        ["They ___ (not / listen) to the teacher.", "aren't listening"],
        ["Look! It ___ (snow)!", "is snowing"],
        ["We ___ (sit) in a cafe right now.", "are sitting"],
        ["___ (he / sleep)?", "Is he sleeping"],
        ["I ___ (not / work) today.", "am not working"],
        ["The kids ___ (run) in the garden.", "are running"],
        ["Why ___ (you / cry)?", "are you crying"]] },
poss: {
  mc: [["This is ___ book. (моя)", "my", "me", "mine", "I"],
       ["Is this ___ phone? (твой)", "your", "you", "yours", "you're"],
       ["___ name is Anna. (её)", "Her", "She", "Hers", "His"],
       ["We love ___ new flat.", "our", "us", "we", "ours"],
       ["That is ___ bike. (велосипед Майка)", "Mike's", "Mike", "Mikes", "of Mike"],
       ["The tree lost ___ leaves.", "its", "it's", "it", "his"],
       ["I know ___ parents. (его)", "his", "him", "he", "he's"],
       ["___ house is very old. (их)", "Their", "There", "They're", "Them"],
       ["This is my ___ room. (комната сестры)", "sister's", "sister", "sisters", "of sister"],
       ["What's ___ phone number? (твой)", "your", "you", "yours", "you're"],
       ["___ dog is very friendly. (наша)", "Our", "Us", "We", "Ours"],
       ["Is that ___ coat? (пальто Анны)", "Anna's", "Anna", "Annas", "of Anna"]],
  tr: [["Это мой телефон.", "This is my phone."],
       ["Как зовут твоего брата?", "What is your brother's name?"],
       ["Её машина красная.", "Her car is red."],
       ["Это комната моего сына.", "This is my son's room."],
       ["Их дети очень милые.", "Their children are very nice.", "Their children are very sweet."],
       ["Наша квартира маленькая.", "Our flat is small.", "Our apartment is small."],
       ["Где его ключи?", "Where are his keys?"],
       ["Это собака моей подруги.", "This is my friend's dog."]],
  gap: [["Is this ___ bag? (твоя)", "your"],
        ["___ brother is a doctor. (мой)", "My"],
        ["Where is ___ bike? (велосипед Лены)", "Lena's"],
        ["They love ___ children. (своих)", "their"],
        ["She lost ___ keys. (свои)", "her"],
        ["We sold ___ old car. (нашу)", "our"],
        ["The bird is building ___ nest. (своё)", "its"],
        ["He forgot ___ umbrella. (свой)", "his"],
        ["Where is ___ office? (офис твоего отца)", "your father's"],
        ["I like ___ new haircut. (её)", "her"]] },
past: {
  mc: [["She ___ a new phone last week.", "bought", "buyed", "buy", "has bought"],
       ["We ___ to Italy in 2019.", "went", "go", "goed", "have gone"],
       ["___ you call your mum yesterday?", "Did", "Do", "Were", "Have"],
       ["I didn't ___ the answer.", "know", "knew", "known", "knows"],
       ["They ___ at home last night.", "were", "was", "are", "did"],
       ["Yesterday he ___ me a funny story.", "told", "telled", "tell", "has told"],
       ["What ___ you do last weekend?", "did", "do", "were", "have"],
       ["I ___ very tired yesterday.", "was", "were", "am", "did"],
       ["We ___ the film. It was boring.", "didn't like", "don't liked", "didn't liked", "not liked"],
       ["She ___ her keys this morning.", "lost", "losed", "lose", "has lose"],
       ["Where ___ you go on holiday last summer?", "did", "do", "were", "have"],
       ["Two years ago I ___ in Paris.", "lived", "live", "have lived", "living"]],
  tr: [["Вчера я ходил в кино.", "Yesterday I went to the cinema.", "I went to the cinema yesterday.", "I went to the movies yesterday."],
       ["Мы встретились в 2018 году.", "We met in 2018."],
       ["Он не пришёл на работу.", "He didn't come to work."],
       ["Что ты делал вчера вечером?", "What did you do last night?", "What did you do yesterday evening?"],
       ["Мне понравился ужин.", "I liked the dinner.", "I enjoyed the dinner."],
       ["Они купили дом в прошлом году.", "They bought a house last year."],
       ["Где ты была в субботу?", "Where were you on Saturday?"],
       ["Я забыл его имя.", "I forgot his name.", "I have forgotten his name."]],
  gap: [["I ___ (see) Tom yesterday.", "saw"],
        ["We ___ (go) to the beach last weekend.", "went"],
        ["She ___ (not / come) to the party last night.", "didn't come"],
        ["___ (you / sleep) well last night?", "Did you sleep"],
        ["They ___ (buy) a new sofa last month.", "bought"],
        ["I ___ (be) at home all day yesterday.", "was"],
        ["He ___ (study) in Berlin in 2015.", "studied"],
        ["Yesterday we ___ (not / have) time to eat.", "didn't have"],
        ["Where ___ (you / meet) your wife?", "did you meet"],
        ["The film ___ (start) at eight last night.", "started"]] },
goingto: {
  mc: [["We ___ visit Paris next summer.", "are going to", "is going to", "going to", "go to"],
       ["He ___ going to buy a car.", "is", "are", "am", "does"],
       ["I'm going to ___ a cake for her birthday.", "make", "makes", "making", "made"],
       ["Look at those clouds! It ___ rain.", "is going to", "goes to", "will to", "going"],
       ["___ you going to call him?", "Are", "Do", "Will", "Is"],
       ["They ___ going to come. They're busy.", "aren't", "don't", "isn't", "not"],
       ["What ___ she going to wear?", "is", "does", "are", "will"],
       ["I'm going ___ learn to drive.", "to", "for", "—", "at"],
       ["Be careful! You ___ fall!", "are going to", "go to", "going to", "are go"],
       ["My sister is going to ___ married in June.", "get", "gets", "getting", "got"],
       ["Where ___ you going to stay?", "are", "do", "is", "will"],
       ["I ___ going to watch that film. It looks boring.", "am not", "don't", "not", "isn't"]],
  tr: [["Я собираюсь купить новый телефон.", "I am going to buy a new phone."],
       ["Мы собираемся пожениться.", "We are going to get married."],
       ["Она собирается сменить работу.", "She is going to change her job.", "She is going to change jobs."],
       ["Ты собираешься ему звонить?", "Are you going to call him?"],
       ["Они не собираются продавать дом.", "They are not going to sell the house.", "They are not going to sell their house."],
       ["Осторожно, ты сейчас упадёшь!", "Careful, you are going to fall!", "Be careful, you are going to fall!"],
       ["Что ты собираешься делать в выходные?", "What are you going to do at the weekend?", "What are you going to do this weekend?", "What are you going to do on the weekend?"],
       ["Я собираюсь лечь спать пораньше.", "I am going to go to bed early.", "I am going to go to bed earlier."]],
  gap: [["I ___ (going to / visit) my grandma tomorrow.", "am going to visit"],
        ["She ___ (going to / start) a new course.", "is going to start"],
        ["We ___ (not / going to / move).", "are not going to move"],
        ["___ (you / going to / help) me?", "Are you going to help"],
        ["It's very cloudy. It ___ (going to / rain).", "is going to rain"],
        ["What ___ (he / going to / say)?", "is he going to say"],
        ["They ___ (going to / have) a baby.", "are going to have"],
        ["I ___ (not / going to / tell) anyone.", "am not going to tell"],
        ["When ___ (you / going to / finish)?", "are you going to finish"],
        ["He ___ (going to / be) late.", "is going to be"]] },
will: {
  mc: [["I think it ___ rain tomorrow.", "will", "is", "does", "rains"],
       ["I promise I ___ tell anyone.", "won't", "don't", "am not", "not will"],
       ["— I'm hungry. — I ___ make you a sandwich.", "'ll", "make", "am make", "would"],
       ["___ you be at home tonight?", "Will", "Do", "Are", "Does"],
       ["She will ___ 30 next year.", "be", "is", "being", "to be"],
       ["Don't worry. Everything ___ be fine.", "will", "is", "does", "would to"],
       ["I ___ help you, I promise.", "will", "am", "do", "going"],
       ["Maybe they ___ come later.", "will", "are", "do", "would to"],
       ["He ___ be late, he's never late.", "won't", "doesn't", "isn't", "not"],
       ["Wait, I ___ carry your bag for you.", "'ll", "carry", "am carry", "would to"],
       ["Do you think people ___ live on Mars one day?", "will", "are", "does", "would to"],
       ["I'm sure you ___ pass the exam.", "will", "are", "do", "would to"]],
  tr: [["Я позвоню тебе завтра.", "I will call you tomorrow."],
       ["Думаю, будет дождь.", "I think it will rain."],
       ["Я обещаю, что не опоздаю.", "I promise I won't be late.", "I promise that I won't be late."],
       ["Ты поможешь мне?", "Will you help me?"],
       ["Всё будет хорошо.", "Everything will be fine.", "Everything will be OK.", "Everything will be all right."],
       ["Я открою дверь.", "I will open the door.", "I will get the door."],
       ["Он не придёт.", "He won't come."],
       ["Мне будет 30 в мае.", "I will be 30 in May.", "I will be thirty in May."]],
  gap: [["I ___ (call) you later.", "will call", "'ll call"],
        ["It ___ (not / take) long.", "won't take"],
        ["___ (you / come) to my party?", "Will you come"],
        ["I think she ___ (like) the present.", "will like", "'ll like"],
        ["I'm tired. I think I ___ (go) to bed.", "will go", "'ll go"],
        ["Don't worry, I ___ (not / tell) your mum.", "won't tell"],
        ["The weather ___ (be) nice tomorrow.", "will be", "'ll be"],
        ["___ (she / be) there?", "Will she be"],
        ["I'm sure they ___ (win) the match.", "will win", "'ll win"],
        ["I ___ (help) you with your bags.", "will help", "'ll help"]] },
comp: {
  mc: [["My car is ___ than yours.", "faster", "more fast", "fastest", "fast"],
       ["This is the ___ day of my life!", "happiest", "happyest", "most happy", "happier"],
       ["English is ___ than Chinese.", "easier", "more easy", "easyer", "easiest"],
       ["He is ___ student in our class.", "the best", "the better", "best", "the goodest"],
       ["Your flat is ___ than mine.", "bigger", "biger", "more big", "biggest"],
       ["This book is ___ than that one.", "more interesting", "interestinger", "most interesting", "interesting"],
       ["Today is ___ than yesterday.", "colder", "more cold", "coldest", "cold"],
       ["She is as tall ___ her mother.", "as", "than", "like", "that"],
       ["Who is the ___ person in your family?", "oldest", "older", "most old", "old"],
       ["My English is ___ than last year.", "better", "gooder", "more good", "best"],
       ["It's the ___ restaurant in the city.", "most expensive", "expensivest", "more expensive", "most expensiver"],
       ["The weather today is ___ than yesterday.", "worse", "badder", "more bad", "worst"]],
  tr: [["Моя сестра старше меня.", "My sister is older than me.", "My sister is older than I am."],
       ["Это лучший день!", "This is the best day!", "It is the best day!"],
       ["Москва больше Петербурга.", "Moscow is bigger than St Petersburg.", "Moscow is bigger than Saint Petersburg."],
       ["Это самый дорогой ресторан в городе.", "This is the most expensive restaurant in the city.", "This is the most expensive restaurant in town."],
       ["Сегодня теплее, чем вчера.", "Today is warmer than yesterday.", "It is warmer today than yesterday."],
       ["Он не такой высокий, как брат.", "He is not as tall as his brother."],
       ["Это худший фильм года.", "This is the worst film of the year.", "This is the worst movie of the year.", "It is the worst film of the year."],
       ["Поезд быстрее автобуса.", "The train is faster than the bus.", "A train is faster than a bus."]],
  gap: [["My brother is ___ (tall) than me.", "taller"],
        ["This is the ___ (cheap) phone in the shop.", "cheapest"],
        ["Russian is ___ (difficult) than English.", "more difficult"],
        ["She is the ___ (good) singer I know.", "best"],
        ["Today is ___ (hot) than yesterday.", "hotter"],
        ["This is the ___ (beautiful) city in the world.", "most beautiful"],
        ["My new job is ___ (bad) than my old one.", "worse"],
        ["He is as ___ (old) as my father.", "old"],
        ["Which is the ___ (long) river in Europe?", "longest"],
        ["Your bag is ___ (heavy) than mine.", "heavier"]] },
some: {
  mc: [["I'd like ___ water, please.", "some", "any", "many", "a"],
       ["We don't have ___ bread.", "any", "some", "many", "a"],
       ["How ___ cups of coffee do you drink a day?", "many", "much", "lot", "any"],
       ["There isn't ___ sugar in my tea.", "much", "many", "a lot", "some"],
       ["Do we have ___ milk?", "any", "many", "a", "an"],
       ["How ___ does it cost?", "much", "many", "lot", "any"],
       ["I have ___ friends in London.", "some", "any", "much", "a"],
       ["She doesn't have ___ free time.", "much", "many", "some", "a lot"],
       ["There are ___ people here today.", "a lot of", "much", "a lot", "any"],
       ["Can I have ___ more tea?", "some", "many", "a", "an"],
       ["I didn't buy ___ eggs.", "any", "some", "much", "a"],
       ["How ___ students are in your group?", "many", "much", "lot", "any"]],
  tr: [["У меня нет денег.", "I don't have any money.", "I have no money."],
       ["Хочешь кофе?", "Would you like some coffee?", "Do you want some coffee?"],
       ["Сколько у тебя времени?", "How much time do you have?", "How much time have you got?"],
       ["В холодильнике есть яйца?", "Are there any eggs in the fridge?"],
       ["У нас много работы.", "We have a lot of work.", "We have lots of work."],
       ["Сколько стоят эти туфли?", "How much are these shoes?", "How much do these shoes cost?"],
       ["У меня есть несколько вопросов.", "I have some questions.", "I have a few questions."],
       ["Там было не очень много людей.", "There weren't many people there.", "There weren't very many people there."]],
  gap: [["Would you like ___ tea? (немного)", "some"],
        ["I don't have ___ questions. (никаких)", "any"],
        ["How ___ water do you drink? (сколько)", "much"],
        ["How ___ brothers do you have? (сколько)", "many"],
        ["Is there ___ cheese left? (какой-нибудь)", "any"],
        ["She has ___ friends in Moscow. (несколько)", "some"],
        ["We don't have ___ time. (много)", "much"],
        ["There are ___ cars in the street. (много, три слова)", "a lot of", "lots of"],
        ["I need ___ help with my homework. (немного)", "some"],
        ["Did you buy ___ apples? (какие-нибудь)", "any"]] },
modal: {
  mc: [["You ___ eat more vegetables. It's good for you.", "should", "must to", "have", "should to"],
       ["Students ___ use phones during the exam.", "mustn't", "don't have to", "should to", "haven't"],
       ["I ___ go to work today. It's a holiday.", "don't have to", "mustn't", "must not", "haven't to"],
       ["He ___ wear a suit at work. It's a rule.", "has to", "have to", "must to", "should to"],
       ["___ I call a doctor?", "Should", "Must to", "Have", "Do"],
       ["You ___ be 18 to drive in Russia.", "have to", "should to", "must to", "has to"],
       ["You ___ tell anyone. It's a secret!", "mustn't", "don't have to", "haven't", "not must"],
       ["Do you ___ work on Saturdays?", "have to", "must", "should to", "has to"],
       ["It's late. We ___ go home.", "should", "should to", "must to", "have"],
       ["She ___ get up early tomorrow — she has a flight.", "has to", "have to", "must to", "should to"],
       ["You ___ come if you don't want to.", "don't have to", "mustn't", "must not", "haven't"],
       ["You ___ drive so fast. It's dangerous.", "shouldn't", "don't have to", "should not to", "haven't to"]],
  tr: [["Тебе стоит отдохнуть.", "You should rest.", "You should have a rest.", "You should take a rest."],
       ["Мне нужно работать в субботу.", "I have to work on Saturday."],
       ["Здесь нельзя курить.", "You mustn't smoke here.", "You can't smoke here.", "Smoking is not allowed here."],
       ["Нам не нужно спешить.", "We don't have to hurry.", "We don't need to hurry."],
       ["Тебе не стоит есть так много.", "You shouldn't eat so much."],
       ["Ему приходится носить очки.", "He has to wear glasses."],
       ["Мне позвонить ему?", "Should I call him?"],
       ["Ты обязательно должен это прочитать!", "You must read this!", "You must read it!"]],
  gap: [["You ___ see this film. It's great! (обязательно должен)", "must"],
        ["I ___ get up early tomorrow. (приходится)", "have to"],
        ["You ___ smoke here. (нельзя)", "mustn't"],
        ["You look tired. You ___ go to bed. (стоит)", "should"],
        ["She ___ wear a uniform at work. (приходится)", "has to"],
        ["You ___ pay. It's free. (не обязательно)", "don't have to"],
        ["What ___ I do? (стоит)", "should"],
        ["You ___ eat so much sugar. (не стоит)", "shouldn't"],
        ["___ work tomorrow? (тебе нужно)", "Do you have to"],
        ["He ___ get up early on Sundays. (ему не нужно)", "doesn't have to"]] },
pp: {
  mc: [["I ___ already seen this film.", "have", "has", "am", "did"],
       ["She has never ___ to London.", "been", "be", "was", "gone to"],
       ["___ you ever eaten sushi?", "Have", "Did", "Has", "Are"],
       ["We ___ finished yet.", "haven't", "didn't", "hasn't", "don't"],
       ["He ___ lost his keys again!", "has", "have", "is", "did"],
       ["I've just ___ an email.", "sent", "send", "sended", "sending"],
       ["Have you ___ your homework yet?", "done", "did", "do", "make"],
       ["They have ___ married for ten years.", "been", "be", "being", "were"],
       ["She ___ broken her leg.", "has", "have", "is", "was"],
       ["I have ___ this book three times.", "read", "readed", "reading", "reads"],
       ["Has he ___ yet?", "arrived", "arrive", "arriving", "arrives"],
       ["We have ___ a lot of new words.", "learned", "learn", "learning", "learns"]],
  tr: [["Я уже сделал это.", "I have already done it.", "I have done it already."],
       ["Ты когда-нибудь был в Париже?", "Have you ever been to Paris?"],
       ["Он только что пришёл.", "He has just arrived.", "He has just come."],
       ["Я никогда не видел снег.", "I have never seen snow."],
       ["Мы ещё не решили.", "We haven't decided yet."],
       ["Она сломала руку.", "She has broken her arm.", "She broke her arm."],
       ["Ты закончил?", "Have you finished?"],
       ["Я потерял телефон.", "I have lost my phone.", "I lost my phone."]],
  gap: [["I ___ (lose) my wallet. I can't find it anywhere.", "have lost"],
        ["She ___ (never / be) to Spain.", "has never been"],
        ["___ (you / ever / try) Thai food?", "Have you ever tried"],
        ["We ___ (just / finish) dinner.", "have just finished"],
        ["He ___ (not / call) yet.", "hasn't called"],
        ["I ___ (already / see) this film.", "have already seen"],
        ["They ___ (buy) a new house. Come and see it!", "have bought"],
        ["___ (she / finish) her work yet?", "Has she finished"],
        ["I ___ (never / eat) oysters.", "have never eaten"],
        ["My parents ___ (go) on holiday. They're in Spain now.", "have gone"]] },
ppvps: {
  mc: [["I ___ to Spain three times in my life.", "have been", "went", "was", "have gone"],
       ["She ___ her job last year.", "lost", "has lost", "have lost", "loses"],
       ["We ___ each other for ten years now.", "have known", "knew", "know", "are knowing"],
       ["When ___ you move to London?", "did", "have", "has", "do"],
       ["He ___ here since January.", "has worked", "worked", "works", "is working"],
       ["___ you ever been to Japan?", "Have", "Did", "Were", "Are"],
       ["They ___ married in 2010.", "got", "have got", "have been", "get"],
       ["I ___ three emails so far today.", "have written", "wrote", "write", "had written"],
       ["How long ___ you lived here?", "have", "did", "do", "are"],
       ["Shakespeare ___ many plays.", "wrote", "has written", "have written", "writes"],
       ["I ___ him since we left school.", "haven't seen", "didn't see", "don't see", "wasn't seeing"],
       ["Last summer we ___ to Greece.", "went", "have been", "have gone", "go"]],
  tr: [["Я знаю его десять лет.", "I have known him for ten years."],
       ["Мы переехали сюда в 2020 году.", "We moved here in 2020."],
       ["Ты когда-нибудь водил грузовик?", "Have you ever driven a truck?", "Have you ever driven a lorry?"],
       ["Она работает здесь с мая.", "She has worked here since May.", "She has been working here since May."],
       ["Я видел этот фильм в прошлом году.", "I saw this film last year.", "I saw this movie last year.", "I watched this film last year."],
       ["Сколько лет ты здесь живёшь?", "How long have you lived here?", "How long have you been living here?"],
       ["Он позвонил мне час назад.", "He called me an hour ago.", "He phoned me an hour ago."],
       ["Я не видел её с прошлой зимы.", "I haven't seen her since last winter."]],
  gap: [["I ___ (live) here since 2015.", "have lived", "have been living"],
        ["We ___ (meet) in 2010.", "met"],
        ["She ___ (work) here for five years now.", "has worked", "has been working"],
        ["I ___ (see) him two days ago.", "saw"],
        ["___ (you / ever / be) to Italy?", "Have you ever been"],
        ["They ___ (get) married last summer.", "got"],
        ["How long ___ (you / know) her?", "have you known"],
        ["When ___ (you / start) learning English?", "did you start"],
        ["I ___ (not / see) him since Monday.", "haven't seen"],
        ["He ___ (leave) the company in 2021.", "left"]] },
pastc: {
  mc: [["At 7 pm yesterday I ___ dinner, so I didn't answer the phone.", "was cooking", "cooked", "am cooking", "cooking"],
       ["She ___ TV when I came in, so she didn't hear me.", "was watching", "watched", "is watching", "watches"],
       ["___ you sleeping when I called?", "Were", "Did", "Was", "Are"],
       ["The students ___ loudly when the teacher came in, and everyone went quiet.", "were talking", "talked", "was talking", "talk"],
       ["I ___ to work when I saw the accident.", "was driving", "drove", "am driving", "drive"],
       ["What ___ you doing at midnight?", "were", "did", "was", "are"],
       ["It ___ when we left the house, so we took umbrellas.", "was raining", "rained", "rains", "is raining"],
       ["While I ___ a shower, the phone rang.", "was taking", "took", "am taking", "take"],
       ["He wasn't ___ when I spoke to him.", "listening", "listen", "listened", "listens"],
       ["We ___ dinner at 8, so we didn't hear the doorbell.", "were having", "had", "have", "was having"],
       ["At that moment she ___ on the phone, so I waited.", "was talking", "talked", "is talking", "talks"],
       ["While we ___ the film, the lights went out.", "were watching", "watched", "are watching", "was watching"]],
  tr: [["Я читал, когда ты позвонил.", "I was reading when you called."],
       ["Что ты делал вчера в девять вечера?", "What were you doing at nine yesterday evening?", "What were you doing at nine last night?", "What were you doing yesterday at nine in the evening?"],
       ["Шёл снег, когда мы вышли.", "It was snowing when we went out.", "It was snowing when we left."],
       ["Она готовила, а я убирался.", "She was cooking and I was cleaning.", "She was cooking while I was cleaning."],
       ["Я не спал, когда ты пришёл.", "I wasn't sleeping when you came."],
       ["Мы ехали домой, когда это случилось.", "We were driving home when it happened.", "We were going home when it happened."],
       ["Ты меня слушал?", "Were you listening to me?"],
       ["Пока я ждал автобус, начался дождь.", "While I was waiting for the bus, it started to rain.", "While I was waiting for the bus, it started raining."]],
  gap: [["I ___ (sleep) when the phone rang.", "was sleeping"],
        ["They ___ (play) cards when we arrived.", "were playing"],
        ["What ___ (you / do) at 10 last night?", "were you doing"],
        ["She ___ (not / listen) to me — she was looking at her phone.", "wasn't listening"],
        ["While he ___ (cook), I set the table.", "was cooking"],
        ["It ___ (rain) all morning yesterday.", "was raining", "rained"],
        ["I ___ (walk) home when I met Kate.", "was walking"],
        ["___ (it / snow) when you left?", "Was it snowing"],
        ["We ___ (have) lunch when the boss called.", "were having"],
        ["The kids ___ (watch) cartoons while I was working.", "were watching"]] },
cond1: {
  mc: [["If you ___ me, I'll help you.", "call", "will call", "called", "calling"],
       ["If it's sunny tomorrow, we ___ to the beach.", "will go", "go", "went", "would go"],
       ["I'll tell him when he ___ home.", "comes", "will come", "came", "coming"],
       ["If she doesn't hurry, she ___ the bus.", "will miss", "misses", "missed", "would miss"],
       ["You won't pass ___ you study.", "unless", "if", "when", "until"],
       ["If I ___ time, I'll visit you.", "have", "will have", "had", "having"],
       ["What will you do if you ___ the job?", "don't get", "won't get", "didn't get", "not get"],
       ["As soon as I ___, I'll text you.", "arrive", "will arrive", "arrived", "arriving"],
       ["If we leave now, we ___ be on time.", "will", "would", "are", "did"],
       ["She'll be angry if you ___ late again.", "are", "will be", "were", "be"],
       ["I'll buy a car if I ___ the money.", "save", "will save", "saved", "saving"],
       ["___ it rains, the match will be cancelled.", "If", "Unless", "Until", "So"]],
  tr: [["Если ты опоздаешь, я уйду.", "If you are late, I will leave."],
       ["Я помогу тебе, если смогу.", "I will help you if I can."],
       ["Если будет холодно, мы останемся дома.", "If it is cold, we will stay at home.", "If it is cold, we will stay home."],
       ["Позвони мне, когда приедешь.", "Call me when you arrive.", "Call me when you get there."],
       ["Если он не придёт, что мы будем делать?", "If he doesn't come, what will we do?", "What will we do if he doesn't come?"],
       ["Ты не похудеешь, если не будешь заниматься спортом.", "You won't lose weight if you don't exercise.", "You won't lose weight unless you exercise."],
       ["Как только я закончу, я тебе позвоню.", "As soon as I finish, I will call you."],
       ["Если я выиграю, я куплю дом.", "If I win, I will buy a house."]],
  gap: [["If it ___ (rain), I will take a taxi.", "rains"],
        ["If you study hard, you ___ (pass) the exam.", "will pass", "'ll pass"],
        ["I ___ (call) you when I get home.", "will call", "'ll call"],
        ["If she ___ (not / come), we will start without her.", "doesn't come"],
        ["We ___ (miss) the train if we don't hurry.", "will miss", "'ll miss"],
        ["If I ___ (see) him, I'll tell him.", "see"],
        ["What ___ (you / do) if you lose your job?", "will you do"],
        ["He won't come unless you ___ (invite) him.", "invite"],
        ["When you ___ (arrive), call me.", "arrive"],
        ["If you ___ (be) hungry, I'll make sandwiches.", "are"]] },
cond2: {
  mc: [["If I ___ more time, I would learn Spanish.", "had", "have", "will have", "would have"],
       ["If he were here, he ___ know what to do.", "would", "will", "is", "does"],
       ["I would buy a house if I ___ enough money.", "had", "have", "would have", "will have"],
       ["If I ___ you, I'd talk to her.", "were", "am", "will be", "be"],
       ["What would you do if you ___ your passport?", "lost", "lose", "will lose", "would lose"],
       ["If we lived in Spain, we ___ to the beach every day.", "would go", "will go", "go", "went"],
       ["She'd be happier if she ___ less.", "worked", "works", "would work", "will work"],
       ["If I could fly, I ___ to Paris right now.", "would fly", "will fly", "fly", "flew"],
       ["I wouldn't do that if I ___ you.", "were", "am", "would be", "will be"],
       ["If he ___ harder, he would get better marks.", "studied", "studies", "would study", "will study"],
       ["Would you help me if I ___ you?", "asked", "ask", "would ask", "will ask"],
       ["If it ___ so cold, we would go for a walk.", "weren't", "isn't", "won't be", "wouldn't be"]],
  tr: [["Если бы я был богат, я бы путешествовал.", "If I were rich, I would travel.", "If I was rich, I would travel."],
       ["На твоём месте я бы ему позвонил.", "If I were you, I would call him."],
       ["Если бы у меня была машина, я бы тебя подвёз.", "If I had a car, I would give you a lift.", "If I had a car, I would give you a ride.", "If I had a car, I would drive you."],
       ["Что бы ты сделал, если бы увидел привидение?", "What would you do if you saw a ghost?"],
       ["Я бы купил этот дом, если бы он был дешевле.", "I would buy this house if it were cheaper.", "I would buy this house if it was cheaper."],
       ["Если бы я знал её номер, я бы позвонил.", "If I knew her number, I would call her.", "If I knew her number, I would call."],
       ["Было бы лучше, если бы ты остался.", "It would be better if you stayed."],
       ["Если бы я мог, я бы помог.", "If I could, I would help.", "If I could, I would help you."]],
  gap: [["If I ___ (have) a dog, I would walk it every day.", "had"],
        ["If I were rich, I ___ (buy) an island.", "would buy", "'d buy"],
        ["If she ___ (know) the answer, she would tell us.", "knew"],
        ["What ___ (you / do) if you won the lottery?", "would you do"],
        ["If I ___ (be) you, I would apologise.", "were", "was"],
        ["He ___ (not / be) so tired if he went to bed earlier.", "wouldn't be"],
        ["If we ___ (live) closer, we would see each other more often.", "lived"],
        ["I ___ (help) you if I had time.", "would help", "'d help"],
        ["If you ___ (not / smoke), you would feel better.", "didn't smoke"],
        ["It would be great if you ___ (can) come.", "could"]] },
passive: {
  mc: [["English ___ all over the world.", "is spoken", "speaks", "is speaking", "spoken"],
       ["The Mona Lisa ___ by Leonardo da Vinci.", "was painted", "painted", "is painting", "has painted"],
       ["Our car ___ every week.", "is washed", "washes", "is washing", "washed"],
       ["The new bridge will ___ next year.", "be built", "build", "built", "be build"],
       ["The window ___ by the children yesterday.", "was broken", "broke", "is broken", "has broken"],
       ["These cars ___ in Japan.", "are made", "make", "are making", "made"],
       ["The letter ___ yesterday.", "was sent", "sent", "is sent", "has sent"],
       ["This book ___ into 50 languages.", "has been translated", "has translated", "translated", "is translating"],
       ["The meeting ___ until next week.", "has been postponed", "has postponed", "postponed", "is postponing"],
       ["Dinner ___ at 7 every evening.", "is served", "serves", "is serving", "served"],
       ["Were you ___ to the party?", "invited", "invite", "inviting", "invites"],
       ["The results will ___ tomorrow.", "be announced", "announce", "announced", "be announce"]],
  tr: [["Этот мост построили в 1900 году.", "This bridge was built in 1900."],
       ["Письма доставляют утром.", "Letters are delivered in the morning.", "The letters are delivered in the morning."],
       ["Его уволили.", "He was fired.", "He was sacked.", "He got fired."],
       ["Этот роман был написан в 1869 году.", "This novel was written in 1869."],
       ["Работа будет закончена в пятницу.", "The work will be finished on Friday.", "The work will be done on Friday."],
       ["Где делают эти телефоны?", "Where are these phones made?"],
       ["Нас не пригласили.", "We weren't invited."],
       ["Дом уже продан.", "The house has already been sold."]],
  gap: [["This house ___ (build) in 1920.", "was built"],
        ["Spanish ___ (speak) in Mexico.", "is spoken"],
        ["The thief ___ (catch) yesterday.", "was caught"],
        ["The letters ___ (send) tomorrow.", "will be sent"],
        ["My car ___ (repair) last week.", "was repaired"],
        ["These shoes ___ (make) in Italy.", "are made"],
        ["The project ___ (already / finish).", "has already been finished"],
        ["The film ___ (direct) by Christopher Nolan.", "was directed"],
        ["We ___ (not / tell) about the changes.", "weren't told"],
        ["___ (the room / clean) every day?", "Is the room cleaned"]] },
usedto: {
  mc: [["We ___ live in a small village.", "used to", "use to", "were used to", "are used to"],
       ["I didn't ___ like fish, but now I love it.", "use to", "used to", "using to", "used"],
       ["He's used to ___ in the cold.", "working", "work", "worked", "works"],
       ["___ you use to play the piano?", "Did", "Were", "Do", "Used"],
       ["She ___ have long hair.", "used to", "use to", "is used to", "uses to"],
       ["I can't get used to ___ on the left.", "driving", "drive", "drove", "drives"],
       ["There ___ be a cinema here.", "used to", "use to", "was used to", "is used to"],
       ["They ___ eat meat, but now they're vegetarians.", "used to", "use to", "are used to", "were used"],
       ["I'm not used to ___ so much.", "eating", "eat", "ate", "eats"],
       ["My dad ___ smoke, but he stopped ten years ago.", "used to", "uses to", "was used to", "use"],
       ["Did she ___ work here?", "use to", "used to", "using to", "uses to"],
       ["You'll soon get used to ___ up early.", "getting", "get", "got", "gets"]],
  tr: [["Раньше я курил.", "I used to smoke."],
       ["Раньше здесь был парк.", "There used to be a park here."],
       ["Я привык рано вставать.", "I am used to getting up early."],
       ["Ты раньше жил в Москве?", "Did you use to live in Moscow?"],
       ["Раньше она не любила кофе.", "She didn't use to like coffee."],
       ["Он привык к шуму.", "He is used to the noise."],
       ["Раньше мы часто ходили в кино.", "We used to go to the cinema a lot.", "We used to go to the cinema often.", "We often used to go to the cinema.", "We used to often go to the cinema."],
       ["Я никак не привыкну к новой работе.", "I can't get used to my new job.", "I can't get used to the new job."]],
  gap: [["I ___ (раньше / play) football every day.", "used to play"],
        ["She ___ (раньше / have) a cat.", "used to have"],
        ["I'm used to ___ (work) at night.", "working"],
        ["___ (you / раньше / live) here?", "Did you use to live"],
        ["He ___ (раньше не / like) vegetables.", "didn't use to like"],
        ["They are used to ___ (drive) in big cities.", "driving"],
        ["There ___ (раньше / be) a shop on this corner.", "used to be"],
        ["We ___ (раньше / go) camping every summer.", "used to go"],
        ["I can't get used to ___ (live) alone.", "living"],
        ["My mum ___ (раньше / work) as a teacher.", "used to work"]] },
rel: {
  mc: [["The man ___ is talking to Anna is my uncle.", "who", "which", "where", "whose"],
       ["The phone ___ I bought last week is broken.", "that", "who", "where", "whose"],
       ["This is the house ___ I grew up.", "where", "which", "who", "what"],
       ["I have a friend ___ brother is a famous actor.", "whose", "who", "which", "who's"],
       ["The film ___ we saw yesterday was great.", "which", "who", "where", "whose"],
       ["Do you know the girl ___ is sitting there?", "who", "which", "where", "what"],
       ["That's the shop ___ sells the best bread.", "that", "who", "where", "whose"],
       ["The hotel ___ we stayed was very nice.", "where", "which", "who", "what"],
       ["She's the teacher ___ helped me a lot.", "who", "which", "whose", "where"],
       ["The car ___ engine broke was very old.", "whose", "which", "who", "that's"],
       ["Is this the book ___ you wanted?", "that", "who", "where", "what"],
       ["People ___ live in glass houses shouldn't throw stones.", "who", "which", "whose", "where"]],
  tr: [["Это женщина, которая живёт рядом.", "This is the woman who lives next door.", "This is the woman who lives nearby."],
       ["Это телефон, который мне подарили.", "This is the phone that I was given.", "This is the phone I was given.", "This is the phone that was given to me."],
       ["Это город, где я вырос.", "This is the town where I grew up.", "This is the city where I grew up."],
       ["Мальчик, чья собака потерялась, плачет.", "The boy whose dog got lost is crying.", "The boy whose dog is lost is crying."],
       ["Книга, которую ты мне дал, очень интересная.", "The book you gave me is very interesting.", "The book that you gave me is very interesting.", "The book which you gave me is very interesting."],
       ["Я знаю человека, который может помочь.", "I know a man who can help.", "I know someone who can help.", "I know a person who can help."],
       ["Это кафе, где мы познакомились.", "This is the cafe where we met."],
       ["Ты видел фильм, о котором я говорил?", "Did you see the film I told you about?", "Have you seen the film I told you about?", "Did you see the film that I told you about?", "Have you seen the film that I told you about?"]],
  gap: [["The woman ___ called you is my boss. (которая)", "who", "that"],
        ["The cake ___ you made was delicious. (который)", "that", "which"],
        ["This is the park ___ we play football. (где)", "where"],
        ["I met a girl ___ father is a pilot. (чей)", "whose"],
        ["The bus ___ goes to the centre is late. (который)", "that", "which"],
        ["He is the actor ___ won the Oscar. (который)", "who", "that"],
        ["That's the restaurant ___ we had our first date. (где)", "where"],
        ["The neighbours ___ dog barks all night are on holiday. (чья)", "whose"],
        ["The keys ___ were on the table are gone. (которые)", "that", "which"],
        ["I don't like people ___ are always late. (которые)", "who", "that"]] },
ger: {
  mc: [["I hope ___ you soon.", "to see", "seeing", "see", "saw"],
       ["She avoids ___ in the rain.", "driving", "to drive", "drive", "drove"],
       ["They decided ___ a house.", "to buy", "buying", "buy", "bought"],
       ["He's good at ___ jokes.", "telling", "to tell", "tell", "told"],
       ["I finished ___ the report.", "writing", "to write", "write", "wrote"],
       ["We plan ___ to Spain in May.", "to go", "going", "go", "went"],
       ["Do you mind ___ for a minute?", "waiting", "to wait", "wait", "waited"],
       ["She promised ___ me.", "to call", "calling", "call", "called"],
       ["I'm thinking about ___ my job.", "changing", "to change", "change", "changed"],
       ["He refused ___ the money.", "to take", "taking", "take", "took"],
       ["Keep ___. You're almost there!", "going", "to go", "go", "went"],
       ["I'd like ___ a table for two.", "to book", "booking", "book", "booked"]],
  tr: [["Я обожаю плавать.", "I love swimming.", "I love to swim.", "I enjoy swimming."],
       ["Она пообещала прийти.", "She promised to come."],
       ["Он бросил курить.", "He stopped smoking.", "He quit smoking.", "He gave up smoking."],
       ["Мы решили остаться дома.", "We decided to stay at home.", "We decided to stay home."],
       ["Я хорошо готовлю.", "I am good at cooking.", "I cook well."],
       ["Не забудь позвонить маме.", "Don't forget to call your mum.", "Don't forget to call mum.", "Don't forget to call your mom."],
       ["Ты не против открыть окно?", "Would you mind opening the window?", "Do you mind opening the window?"],
       ["Я надеюсь найти работу.", "I hope to find a job."]],
  gap: [["I enjoy ___ (cook) for my friends.", "cooking"],
        ["She wants ___ (become) a doctor.", "to become"],
        ["He finished ___ (paint) the room.", "painting"],
        ["We hope ___ (see) you soon.", "to see"],
        ["Thank you for ___ (come).", "coming"],
        ["I decided ___ (learn) English.", "to learn"],
        ["She is afraid of ___ (fly).", "flying"],
        ["Would you like ___ (dance)?", "to dance"],
        ["Stop ___ (talk), please.", "talking"],
        ["They agreed ___ (help) us.", "to help"]] },
cond3: {
  mc: [["If you had told me, I ___ you.", "would have helped", "would help", "had helped", "helped"],
       ["If we ___ the map, we wouldn't have got lost.", "had taken", "took", "would have taken", "have taken"],
       ["She would have passed if she ___ harder.", "had studied", "studied", "would study", "has studied"],
       ["If I had known you were ill, I ___ visited you.", "would have", "would", "had", "will have"],
       ["If he hadn't been late, he ___ the job.", "would have got", "would get", "had got", "got"],
       ["We ___ the match if we had played better.", "would have won", "would win", "had won", "won"],
       ["If it hadn't rained, we ___ a picnic.", "would have had", "would have", "had had", "will have"],
       ["If you ___ your phone, I could have called you.", "had charged", "charged", "would charge", "have charged"],
       ["I wouldn't have known if you ___ me.", "hadn't told", "didn't tell", "wouldn't tell", "haven't told"],
       ["If she had left earlier, she ___ here now.", "would be", "would have been", "will be", "had been"],
       ["If I ___ that, I would have stopped.", "had seen", "saw", "would see", "have seen"],
       ["They would have come if you ___ them.", "had invited", "invited", "would invite", "have invited"]],
  tr: [["Если бы ты меня разбудил, я бы не опоздал.", "If you had woken me up, I wouldn't have been late.", "If you had woken me, I wouldn't have been late."],
       ["Если бы я знал, я бы тебе сказал.", "If I had known, I would have told you."],
       ["Мы бы выиграли, если бы играли лучше.", "We would have won if we had played better."],
       ["Если бы она не позвонила, я бы забыл.", "If she hadn't called, I would have forgotten."],
       ["Если бы я тогда купил квартиру, я бы сейчас был богат.", "If I had bought a flat then, I would be rich now.", "If I had bought an apartment then, I would be rich now."],
       ["Что бы ты сделал, если бы опоздал на самолёт?", "What would you have done if you had missed the plane?", "What would you have done if you had missed the flight?"],
       ["Если бы шёл дождь, мы бы остались дома.", "If it had rained, we would have stayed at home.", "If it had rained, we would have stayed home."],
       ["Я бы пришёл, если бы ты меня пригласил.", "I would have come if you had invited me."]],
  gap: [["If I ___ (know) about the party, I would have come.", "had known"],
        ["If she had asked, I ___ (help) her.", "would have helped"],
        ["We ___ (not / get) lost if we had used the map.", "wouldn't have got", "wouldn't have gotten"],
        ["If you ___ (not / forget) the tickets, we would be in the theatre now.", "hadn't forgotten"],
        ["He would have won if he ___ (train) harder.", "had trained"],
        ["If they ___ (leave) earlier, they would have caught the train.", "had left"],
        ["What ___ (you / do) if you had lost your passport?", "would you have done"],
        ["If I had taken that job, I ___ (live) in London now.", "would live", "would be living"],
        ["If it ___ (not / rain), we would have gone to the beach.", "hadn't rained"],
        ["She ___ (be) happier if she had married Tom.", "would have been", "would be"]] },
rep: {
  mc: [["She said she ___ busy.", "was", "be", "been", "being"],
       ["He told me he ___ call later.", "would", "will to", "would to", "shall to"],
       ["He asked me why I ___ late.", "was", "be", "been", "being"],
       ["He asked ___ I liked the film.", "if", "that", "what", "do"],
       ["They ___ us that the hotel was full.", "told", "said", "spoke", "asked"],
       ["She ___ that she was tired.", "said", "told", "spoke", "talked"],
       ["He said that he ___ already eaten.", "had", "have", "was", "did"],
       ["The teacher told us ___ talk.", "not to", "don't", "no", "not"],
       ["She asked me ___ I was from.", "where", "that", "if", "what"],
       ["He asked me what time it ___.", "was", "is it", "was it", "does"],
       ["He said he ___ come the next day.", "couldn't", "can't to", "couldn't to", "not can"],
       ["She asked me ___ I could help her.", "whether", "that", "what", "do"]],
  tr: [["Она сказала, что занята.", "She said that she was busy.", "She said she was busy."],
       ["Он сказал мне, что опоздает.", "He told me that he would be late.", "He told me he would be late."],
       ["Она спросила, где я работаю.", "She asked where I worked.", "She asked me where I worked."],
       ["Он спросил, люблю ли я кофе.", "He asked if I liked coffee.", "He asked me if I liked coffee.", "He asked whether I liked coffee.", "He asked me whether I liked coffee."],
       ["Я сказал ей не волноваться.", "I told her not to worry."],
       ["Они сказали, что уже поели.", "They said that they had already eaten.", "They said they had already eaten."],
       ["Она попросила меня закрыть дверь.", "She asked me to close the door."],
       ["Он сказал, что позвонит на следующий день.", "He said that he would call the next day.", "He said he would call the next day."]],
  gap: [["«I am tired.» → He said he ___ tired. (be)", "was"],
        ["«I will help you.» → She said she ___ me. (help)", "would help"],
        ["«Where do you live?» → He asked where I ___. (live)", "lived"],
        ["«Are you OK?» → She asked ___ I was OK. (ли)", "if", "whether"],
        ["«I have finished.» → He said he ___. (finish)", "had finished"],
        ["«Don't be late!» → She told me ___ late. (не опаздывать)", "not to be"],
        ["«I can swim.» → He said he ___. (can / swim)", "could swim"],
        ["«I'm working.» → She said she ___. (work)", "was working"],
        ["«Call me!» → He told me ___ him. (позвонить)", "to call"],
        ["«I saw the film.» → She said she ___ the film. (see)", "had seen", "saw"]] },
ppc: {
  mc: [["I ___ here for two hours!", "have been sitting", "am sitting", "sit", "sat"],
       ["How long ___ you been waiting?", "have", "are", "do", "did"],
       ["She's out of breath because she ___.", "has been running", "is running", "runs", "run"],
       ["They ___ English since 2020.", "have been learning", "are learning", "learn", "learned"],
       ["It ___ all day. The streets are wet.", "has been raining", "is raining", "rains", "rain"],
       ["What have you ___ doing lately?", "been", "being", "be", "was"],
       ["I ___ this book for a week and I still haven't finished it.", "have been reading", "am reading", "read", "reads"],
       ["He ___ for this company since he left school.", "has been working", "is working", "works", "worked"],
       ["Your eyes are red. ___ you been crying?", "Have", "Are", "Did", "Do"],
       ["We have been ___ about moving to the countryside.", "thinking", "think", "thought", "thinks"],
       ["How long has she ___ playing the violin?", "been", "being", "be", "was"],
       ["I'm tired. I ___ all morning.", "have been cleaning", "am cleaning", "clean", "cleans"]],
  tr: [["Я учу английский два года.", "I have been learning English for two years.", "I have been studying English for two years."],
       ["Как долго ты здесь работаешь?", "How long have you been working here?"],
       ["Мы ждём автобус уже двадцать минут.", "We have been waiting for the bus for twenty minutes.", "We have been waiting for the bus for 20 minutes."],
       ["Она плачет с утра.", "She has been crying since morning.", "She has been crying since the morning."],
       ["Чем ты занимался в последнее время?", "What have you been doing lately?", "What have you been doing recently?"],
       ["Он смотрит телевизор весь день.", "He has been watching TV all day."],
       ["Я думаю об этом всю неделю.", "I have been thinking about it all week.", "I have been thinking about this all week."],
       ["Они живут здесь с 2010 года.", "They have been living here since 2010.", "They have lived here since 2010."]],
  gap: [["I ___ (wait) for you for an hour!", "have been waiting"],
        ["How long ___ (you / learn) English?", "have you been learning"],
        ["She ___ (work) here since 2018.", "has been working", "has worked"],
        ["It ___ (snow) all night.", "has been snowing"],
        ["They ___ (talk) on the phone for ages.", "have been talking"],
        ["What ___ (you / do) all day?", "have you been doing"],
        ["He's tired because he ___ (run).", "has been running"],
        ["We ___ (look) for a new flat since May.", "have been looking"],
        ["How long ___ (she / play) the piano?", "has she been playing"],
        ["I ___ (not / sleep) well lately.", "haven't been sleeping"]] },
deduct: {
  mc: [["He isn't answering. He ___ asleep.", "must be", "must have", "can't be", "should be"],
       ["The window is broken. Someone ___ thrown a ball.", "must have", "can't have", "should have", "must"],
       ["She ___ left already — her coat is still here.", "can't have", "must have", "should have", "can't"],
       ["I ___ studied more. I failed the exam.", "should have", "must have", "can't have", "should"],
       ["They're late. They ___ got stuck in traffic.", "might have", "can't have", "should have", "might"],
       ["You ___ seen him yesterday — he was in Paris.", "can't have", "must have", "should have", "can"],
       ["The ground is wet. It ___ rained at night.", "must have", "can't have", "should have", "must"],
       ["We ___ booked a table. The restaurant is full.", "should have", "must have", "can't have", "should"],
       ["He looks very happy. He ___ passed the exam.", "must have", "can't have", "should have", "must"],
       ["I can't find my keys. I ___ left them at work.", "might have", "can't have", "should", "might"],
       ["You ___ told her! It was a secret!", "shouldn't have", "mustn't have", "can't have", "shouldn't"],
       ["She ___ forgotten — I reminded her twice.", "can't have", "must have", "should have", "mustn't"]],
  tr: [["Он, должно быть, ушёл.", "He must have left.", "He must have gone."],
       ["Она не могла этого сказать.", "She can't have said that.", "She couldn't have said that."],
       ["Тебе следовало мне позвонить.", "You should have called me.", "You should have phoned me."],
       ["Возможно, я оставил телефон в машине.", "I might have left my phone in the car.", "I may have left my phone in the car."],
       ["Мне не следовало этого есть.", "I shouldn't have eaten that.", "I shouldn't have eaten it."],
       ["Они, должно быть, очень устали.", "They must be very tired."],
       ["Он не мог забыть.", "He can't have forgotten.", "He couldn't have forgotten."],
       ["Вам следовало прийти раньше.", "You should have come earlier."]],
  gap: [["He ___ about the meeting. (должно быть, забыл)", "must have forgotten"],
        ["She ___ us. It was too dark. (не могла видеть)", "can't have seen", "couldn't have seen"],
        ["You ___ me the truth. (следовало сказать)", "should have told"],
        ["They ___ the bus. (возможно, опоздали на)", "might have missed", "may have missed", "could have missed"],
        ["I ___ this jacket. It's too small. (не следовало покупать)", "shouldn't have bought"],
        ["The door is open. Somebody ___ in. (должно быть, вошёл)", "must have come", "must have got"],
        ["We ___ earlier. Now we're late. (следовало выйти)", "should have left"],
        ["He ___ it. He was with me all day. (не мог сделать)", "can't have done", "couldn't have done"],
        ["She ___ ill yesterday. (возможно, была)", "might have been", "may have been", "could have been"],
        ["You look exhausted. You ___ hard. (должно быть, работал)", "must have been working", "must have worked"]] },
wish: {
  mc: [["I wish I ___ speak French.", "could", "can", "will", "would can"],
       ["I wish I ___ to the party yesterday.", "had gone", "went", "go", "would go"],
       ["She wishes she ___ in a bigger flat.", "lived", "lives", "will live", "has lived"],
       ["I wish it ___ raining.", "would stop", "stops", "will stop", "stopped to"],
       ["If only I ___ his number!", "knew", "know", "will know", "had know"],
       ["I wish I ___ so much last night.", "hadn't eaten", "didn't eat", "don't eat", "wouldn't eat"],
       ["He wishes he ___ younger.", "were", "is", "will be", "be"],
       ["I wish you ___ me earlier.", "had told", "tell", "have told", "would told"],
       ["I wish my neighbours ___ so noisy.", "weren't", "aren't", "won't be", "haven't been"],
       ["She wishes she ___ that job last year.", "had taken", "takes", "will take", "has taken"],
       ["I wish you ___ complaining all the time!", "would stop", "stop", "will stop", "are stopping"],
       ["I broke my phone. If only I ___ more careful!", "had been", "am", "will be", "have been"]],
  tr: [["Жаль, что я не умею плавать.", "I wish I could swim."],
       ["Жаль, что ты не пришёл.", "I wish you had come."],
       ["Хотел бы я быть выше.", "I wish I were taller.", "I wish I was taller."],
       ["Жаль, что я не знаю ответа.", "I wish I knew the answer."],
       ["Жаль, что мы не поехали.", "I wish we had gone."],
       ["Хоть бы дождь прекратился!", "I wish it would stop raining!", "I wish the rain would stop!"],
       ["Если бы только у меня было больше времени!", "If only I had more time!"],
       ["Жаль, что я его не послушал.", "I wish I had listened to him."]],
  gap: [["I wish I ___ (have) more free time.", "had"],
        ["I wish I ___ (not / say) that.", "hadn't said"],
        ["She wishes she ___ (can) drive.", "could"],
        ["I wish you ___ (stop) shouting.", "would stop"],
        ["If only I ___ (know) earlier!", "had known"],
        ["He wishes he ___ (live) by the sea.", "lived"],
        ["I wish I ___ (study) harder at school.", "had studied"],
        ["I wish it ___ (be) summer.", "were", "was"],
        ["We wish we ___ (buy) that house when it was cheap.", "had bought"],
        ["I wish my brother ___ (call) me more often.", "would call", "called"]] },
fut: {
  mc: [["At 10 am tomorrow I ___ in a meeting, so I can't talk.", "will be sitting", "will sit", "sit", "will have sat"],
       ["By next year she ___ her degree.", "will have finished", "will finish", "finishes", "will be finishing"],
       ["This time next week we ___ on the beach.", "will be lying", "will lie", "lie", "will have lain"],
       ["By the time you get home, I ___ dinner.", "will have cooked", "will cook", "cook", "am cooking"],
       ["Don't phone at 9 — I ___ my favourite show.", "will be watching", "will have watched", "watch", "watched"],
       ["By 2030 they ___ the new airport.", "will have built", "will build", "build", "are building"],
       ["Will you ___ the car tonight? I need it.", "be using", "have used", "use to", "used"],
       ["By the end of the month I ___ 300 new words.", "will have learned", "will learn", "learn", "am learning"],
       ["By 6 o'clock the plane ___ in Moscow.", "will have landed", "will be landing", "lands", "landed"],
       ["Tomorrow at noon I ___ to Paris.", "will be flying", "will have flown", "fly", "flew"],
       ["He ___ the work by Monday.", "will have done", "will be doing", "does", "did"],
       ["What ___ you be doing at 8 tonight?", "will", "are", "do", "have"]],
  tr: [["Завтра в шесть я буду работать.", "At six tomorrow I will be working.", "I will be working at six tomorrow.", "Tomorrow at six I will be working."],
       ["К вечеру я закончу.", "I will have finished by the evening.", "By the evening I will have finished.", "I will have finished by evening."],
       ["В это время в следующем месяце мы будем отдыхать в Турции.", "This time next month we will be relaxing in Turkey.", "This time next month we will be on holiday in Turkey."],
       ["К пятнице я прочитаю книгу.", "By Friday I will have read the book.", "I will have read the book by Friday."],
       ["Ты будешь пользоваться компьютером вечером?", "Will you be using the computer this evening?", "Will you be using the computer tonight?"],
       ["К тому времени, как ты проснёшься, я уже уйду.", "By the time you wake up, I will have left.", "I will have left by the time you wake up."],
       ["Не приходи в семь, я буду спать.", "Don't come at seven, I will be sleeping."],
       ["К концу года мы переедем.", "By the end of the year we will have moved.", "We will have moved by the end of the year."]],
  gap: [["This time tomorrow I ___ (fly) to London.", "will be flying"],
        ["By Monday I ___ (finish) the project.", "will have finished"],
        ["Don't call at 7 — we ___ (have) dinner.", "will be having"],
        ["By the time you arrive, the film ___ (start).", "will have started"],
        ["At midnight I ___ (sleep).", "will be sleeping"],
        ["By next summer she ___ (save) enough money.", "will have saved"],
        ["___ (you / use) your car tomorrow?", "Will you be using"],
        ["By 2030 I ___ (work) here for 20 years.", "will have worked", "will have been working"],
        ["This time next year they ___ (live) in Canada.", "will be living"],
        ["By the end of the day we ___ (sell) all the tickets.", "will have sold"]] }

};
if (typeof GRAMMAR !== "undefined") GRAMMAR.forEach(g => {
  const x = GRAMMAR_EXT[g.id]; if (!x) return;
  g.mc.push(...(x.mc || [])); g.tr.push(...(x.tr || [])); g.gap = (g.gap || []).concat(x.gap || []);
});
