/* Тексты для чтения и перевода — длиннее обычных, по уровням.
   Формат как у TEXTS в course.js: пары «предложение | перевод».
   Все тексты написаны для приложения. */
const READING = [
{ id: "r1", lvl: "A1", title: "My best friend", pairs: [
  ["My best friend is called Sasha.", "Моего лучшего друга зовут Саша."],
  ["We met at school when we were seven.", "Мы познакомились в школе, когда нам было семь."],
  ["Sasha is tall and he has short black hair.", "Саша высокий, у него короткие чёрные волосы."],
  ["He is very funny and he always makes me laugh.", "Он очень смешной и всегда меня смешит."],
  ["Now he lives in another city, but we talk every week.", "Сейчас он живёт в другом городе, но мы созваниваемся каждую неделю."],
  ["In summer he comes to visit me.", "Летом он приезжает ко мне в гости."],
  ["We go fishing, play football and eat a lot of pizza.", "Мы ходим на рыбалку, играем в футбол и едим много пиццы."],
  ["A good friend is like a brother.", "Хороший друг — как брат."]] },
{ id: "r2", lvl: "A1", title: "A day off", pairs: [
  ["Today is Saturday, and I don't have to work.", "Сегодня суббота, и мне не надо на работу."],
  ["I wake up at ten o'clock.", "Я просыпаюсь в десять часов."],
  ["I make coffee and eggs and eat breakfast on the balcony.", "Я делаю кофе и яичницу и завтракаю на балконе."],
  ["The weather is warm and sunny.", "Погода тёплая и солнечная."],
  ["In the afternoon I meet my friends in the park.", "Днём я встречаюсь с друзьями в парке."],
  ["We walk, talk and buy ice cream.", "Мы гуляем, болтаем и покупаем мороженое."],
  ["In the evening I watch a film at home.", "Вечером я смотрю фильм дома."],
  ["It is a perfect day.", "Это идеальный день."]] },
{ id: "r3", lvl: "A1", title: "My city", pairs: [
  ["I live in Chelyabinsk.", "Я живу в Челябинске."],
  ["It is a big city in the Urals.", "Это большой город на Урале."],
  ["There are many factories, shops and parks here.", "Здесь много заводов, магазинов и парков."],
  ["Winters are long and very cold.", "Зимы долгие и очень холодные."],
  ["Summers are short, but they are warm.", "Лето короткое, но тёплое."],
  ["There are a lot of lakes near the city.", "Рядом с городом много озёр."],
  ["People often go there at the weekend.", "Люди часто ездят туда на выходных."],
  ["My favourite place is the old street in the centre.", "Моё любимое место — старая улица в центре."]] },
{ id: "r4", lvl: "A2", title: "The lost dog", pairs: [
  ["Last Sunday I was walking in the park when I saw a small brown dog.", "В прошлое воскресенье я гулял в парке и увидел маленькую коричневую собаку."],
  ["It was alone and looked very scared.", "Она была одна и выглядела очень испуганной."],
  ["It had a collar, but there was no phone number on it.", "На ней был ошейник, но номера телефона на нём не было."],
  ["I gave it some water and took a photo.", "Я дал ей воды и сфотографировал."],
  ["Then I posted the photo in a local group online.", "Потом я выложил фото в местную группу в интернете."],
  ["An hour later, a woman called me.", "Через час мне позвонила женщина."],
  ["She was crying because she had looked for the dog all morning.", "Она плакала, потому что искала собаку всё утро."],
  ["When the dog saw her, it started jumping with joy.", "Когда собака её увидела, она начала прыгать от радости."],
  ["The woman thanked me again and again.", "Женщина снова и снова меня благодарила."],
  ["It was the best part of my weekend.", "Это была лучшая часть моих выходных."]] },
{ id: "r5", lvl: "A2", title: "First day at a new job", pairs: [
  ["I was very nervous on my first day at the new company.", "В первый день в новой компании я очень нервничал."],
  ["I got up early, put on my best shirt and left home an hour before work.", "Я рано встал, надел лучшую рубашку и вышел из дома за час до работы."],
  ["My manager showed me the office and introduced me to the team.", "Мой руководитель показал мне офис и познакомил с командой."],
  ["Everybody was friendly, but I forgot all their names in five minutes.", "Все были дружелюбными, но я забыл все их имена через пять минут."],
  ["At lunch, a colleague invited me to a small cafe nearby.", "В обед коллега пригласил меня в маленькое кафе неподалёку."],
  ["We talked about films, music and our cities.", "Мы говорили о фильмах, музыке и наших городах."],
  ["In the afternoon I had to learn a new computer program.", "Днём мне пришлось осваивать новую программу."],
  ["It was difficult, but my colleagues helped me.", "Было трудно, но коллеги мне помогли."],
  ["When I got home, I was tired but happy.", "Когда я пришёл домой, я был уставшим, но счастливым."]] },
{ id: "r6", lvl: "A2", title: "A birthday surprise", pairs: [
  ["My sister's birthday was on Friday, and we decided to surprise her.", "У сестры в пятницу был день рождения, и мы решили сделать ей сюрприз."],
  ["Her husband took her to the cinema, and we went to their flat.", "Её муж повёл её в кино, а мы пошли к ним в квартиру."],
  ["We put balloons everywhere and prepared a big cake.", "Мы развесили везде шарики и приготовили большой торт."],
  ["Then we turned off the lights and waited in the dark.", "Потом мы выключили свет и ждали в темноте."],
  ["At nine o'clock we heard the key in the door.", "В девять часов мы услышали ключ в двери."],
  ["When she opened the door, everybody shouted 'Surprise!'", "Когда она открыла дверь, все закричали: «Сюрприз!»"],
  ["She was so shocked that she dropped her bag.", "Она была так потрясена, что уронила сумку."],
  ["Then she started laughing and hugged everyone.", "Потом она засмеялась и всех обняла."],
  ["We danced and talked until two in the morning.", "Мы танцевали и болтали до двух часов ночи."]] },
{ id: "r7", lvl: "A2", title: "A weekend in the mountains", pairs: [
  ["Last month my friends and I went to the mountains for the weekend.", "В прошлом месяце мы с друзьями поехали на выходные в горы."],
  ["We rented a small wooden house near a lake.", "Мы сняли маленький деревянный дом у озера."],
  ["On Saturday we climbed the highest mountain in the area.", "В субботу мы поднялись на самую высокую гору в округе."],
  ["It took us four hours to get to the top.", "Подъём на вершину занял у нас четыре часа."],
  ["The view was amazing: forests, lakes and clouds below us.", "Вид был потрясающий: леса, озёра и облака под нами."],
  ["In the evening we cooked dinner on a fire and sang songs.", "Вечером мы готовили ужин на костре и пели песни."],
  ["There was no internet, and nobody missed it.", "Интернета не было, и никто по нему не скучал."],
  ["On Sunday it rained, so we played cards all day.", "В воскресенье шёл дождь, и мы весь день играли в карты."],
  ["I want to go back there next summer.", "Я хочу вернуться туда следующим летом."]] },
{ id: "r8", lvl: "B1", title: "The man who planted trees", pairs: [
  ["In a small village there lived an old man who had lost his family many years ago.", "В маленькой деревне жил старик, который много лет назад потерял семью."],
  ["The land around the village was dry and empty, and most young people had left.", "Земля вокруг деревни была сухой и пустой, и почти вся молодёжь уехала."],
  ["Every morning the old man took a bag of seeds and walked into the hills.", "Каждое утро старик брал мешок семян и уходил в холмы."],
  ["He planted one tree after another, without asking anyone for help.", "Он сажал одно дерево за другим, ни у кого не прося помощи."],
  ["People laughed at him and said it was a waste of time.", "Люди смеялись над ним и говорили, что это пустая трата времени."],
  ["Many of the trees died, but he never gave up.", "Многие деревья погибли, но он никогда не сдавался."],
  ["Twenty years later, the hills were covered with a young forest.", "Через двадцать лет холмы покрылись молодым лесом."],
  ["The rain came back, rivers appeared, and families started returning to the village.", "Вернулись дожди, появились реки, и семьи начали возвращаться в деревню."],
  ["Nobody remembered who had planted the trees.", "Никто не помнил, кто посадил эти деревья."],
  ["But the forest was there, and that was enough for him.", "Но лес был, и ему этого было достаточно."]] },
{ id: "r9", lvl: "B1", title: "A strange phone call", pairs: [
  ["One evening my phone rang, and a man said, 'Hello, is that you, Mike?'", "Однажды вечером зазвонил телефон, и мужчина сказал: «Алло, это ты, Майк?»"],
  ["I told him that he had the wrong number.", "Я сказал ему, что он ошибся номером."],
  ["Five minutes later he called again and asked the same question.", "Через пять минут он позвонил снова и задал тот же вопрос."],
  ["This time I asked who he was trying to reach.", "На этот раз я спросил, до кого он пытается дозвониться."],
  ["He explained that he hadn't seen his old friend Mike for thirty years.", "Он объяснил, что не видел своего старого друга Майка тридцать лет."],
  ["Someone had given him this number, but it was probably a mistake.", "Кто-то дал ему этот номер, но, видимо, это была ошибка."],
  ["We ended up talking for almost an hour about friendship and how fast life goes.", "В итоге мы проговорили почти час о дружбе и о том, как быстро летит жизнь."],
  ["Before he hung up, I promised to help him search online.", "Прежде чем он повесил трубку, я пообещал помочь поискать в интернете."],
  ["Two days later we found Mike on social media.", "Через два дня мы нашли Майка в соцсетях."],
  ["Now I get a message from both of them every New Year.", "Теперь каждый Новый год мне приходит сообщение от них обоих."]] },
{ id: "r10", lvl: "B1", title: "A short history of coffee", pairs: [
  ["According to a legend, coffee was discovered in Ethiopia by a goat herder.", "По легенде, кофе открыл в Эфиопии пастух коз."],
  ["He noticed that his goats became very energetic after eating red berries from a certain bush.", "Он заметил, что его козы становились очень бодрыми, поев красных ягод с одного куста."],
  ["Later, people in Yemen started roasting the beans and making a hot drink from them.", "Позже в Йемене начали обжаривать зёрна и делать из них горячий напиток."],
  ["By the seventeenth century, coffee houses had appeared all over Europe.", "К семнадцатому веку кофейни появились по всей Европе."],
  ["They became places where people met to discuss news, politics and business.", "Они стали местами, где люди собирались обсуждать новости, политику и дела."],
  ["Some rulers even tried to ban coffee because they were afraid of these discussions.", "Некоторые правители даже пытались запретить кофе, потому что боялись этих разговоров."],
  ["Today, coffee is one of the most popular drinks in the world.", "Сегодня кофе — один из самых популярных напитков в мире."],
  ["Every day people drink more than two billion cups of it.", "Каждый день люди выпивают больше двух миллиардов чашек."]] },
{ id: "r11", lvl: "B1", title: "Living abroad", pairs: [
  ["Moving to another country sounds exciting, and in many ways it is.", "Переезд в другую страну звучит захватывающе, и во многом так и есть."],
  ["However, the first months are often harder than people expect.", "Однако первые месяцы часто оказываются труднее, чем люди ожидают."],
  ["Simple things, like opening a bank account or seeing a doctor, suddenly become a challenge.", "Простые вещи, например открыть счёт в банке или сходить к врачу, вдруг становятся испытанием."],
  ["You don't understand the jokes, and people speak much faster than in your textbook.", "Ты не понимаешь шуток, а люди говорят гораздо быстрее, чем в учебнике."],
  ["Many people feel lonely and homesick at this stage.", "На этом этапе многие чувствуют одиночество и тоску по дому."],
  ["The good news is that it usually gets better after about six months.", "Хорошая новость в том, что обычно примерно через полгода становится лучше."],
  ["You make friends, find your favourite places and start to feel at home.", "Ты заводишь друзей, находишь любимые места и начинаешь чувствовать себя как дома."],
  ["The language, which seemed impossible, slowly becomes part of your daily life.", "Язык, который казался невозможным, постепенно становится частью повседневной жизни."]] },
{ id: "r12", lvl: "B2", title: "The paradox of choice", pairs: [
  ["We tend to assume that the more options we have, the happier we will be.", "Мы склонны считать, что чем больше у нас вариантов, тем счастливее мы будем."],
  ["Psychologists, however, have found that too much choice can actually make us less satisfied.", "Однако психологи обнаружили, что слишком большой выбор может, наоборот, делать нас менее довольными."],
  ["In one famous experiment, a shop offered customers either six or twenty-four types of jam.", "В одном известном эксперименте магазин предлагал покупателям то шесть, то двадцать четыре вида джема."],
  ["The larger display attracted more attention, but far fewer people bought anything.", "Большая витрина привлекала больше внимания, но покупали гораздо меньше людей."],
  ["When faced with endless possibilities, we are afraid of making the wrong decision.", "Когда перед нами бесконечные варианты, мы боимся принять неправильное решение."],
  ["Even after choosing, we keep wondering whether another option would have been better.", "Даже сделав выбор, мы продолжаем гадать, не был ли другой вариант лучше."],
  ["This doesn't mean that choice is bad, but it suggests that limiting our options can be a relief.", "Это не значит, что выбор — это плохо, но говорит о том, что ограничение вариантов может принести облегчение."],
  ["Sometimes 'good enough' is exactly what we need.", "Иногда «достаточно хорошо» — именно то, что нам нужно."]] },
{ id: "r13", lvl: "B2", title: "Can money buy happiness?", pairs: [
  ["For decades, researchers have tried to answer a simple question: does money make people happier?", "Десятилетиями исследователи пытаются ответить на простой вопрос: делают ли деньги людей счастливее?"],
  ["The answer turns out to be more complicated than a simple yes or no.", "Ответ оказывается сложнее, чем просто «да» или «нет»."],
  ["Up to a certain point, more income clearly improves people's lives, because it reduces stress about basic needs.", "До определённого уровня рост дохода явно улучшает жизнь, потому что снижает тревогу о базовых потребностях."],
  ["Beyond that point, the effect becomes much weaker.", "Выше этого уровня эффект становится гораздо слабее."],
  ["Interestingly, how we spend money seems to matter more than how much we have.", "Интересно, что то, как мы тратим деньги, похоже, важнее того, сколько их у нас."],
  ["People who spend on experiences, such as travel or concerts, tend to be happier than those who buy more things.", "Люди, которые тратят деньги на впечатления, например путешествия или концерты, обычно счастливее тех, кто покупает больше вещей."],
  ["Spending money on others also brings more lasting joy than spending it on ourselves.", "Траты на других тоже приносят более долгую радость, чем траты на себя."],
  ["So perhaps the real question is not how to earn more, but how to use what we have wisely.", "Так что, возможно, настоящий вопрос не в том, как заработать больше, а в том, как с умом распорядиться тем, что есть."]] },
{ id: "r14", lvl: "B2", title: "Why we forget", pairs: [
  ["Most of what we learn disappears from our memory within a few days.", "Большая часть того, что мы узнаём, исчезает из памяти за несколько дней."],
  ["In the nineteenth century, Hermann Ebbinghaus measured this process and described the so-called forgetting curve.", "В девятнадцатом веке Герман Эббингауз измерил этот процесс и описал так называемую кривую забывания."],
  ["He discovered that memories fade quickly at first and then more slowly.", "Он обнаружил, что воспоминания сначала угасают быстро, а потом медленнее."],
  ["Crucially, each time we review information just before forgetting it, the curve becomes flatter.", "Самое важное: каждый раз, когда мы повторяем информацию незадолго до того, как забыть её, кривая становится более пологой."],
  ["This is the principle behind spaced repetition, which language apps use today.", "На этом принципе основаны интервальные повторения, которые сегодня используют приложения для изучения языков."],
  ["Another key factor is the effort of recalling: struggling to remember a word strengthens the memory far more than simply rereading it.", "Ещё один ключевой фактор — усилие при вспоминании: попытка вспомнить слово укрепляет память гораздо сильнее, чем простое перечитывание."],
  ["Sleep also plays a vital role, as the brain consolidates new information at night.", "Сон тоже играет важнейшую роль, ведь ночью мозг закрепляет новую информацию."],
  ["In other words, forgetting is not a failure; it is part of how learning works.", "Иными словами, забывание — это не провал, а часть того, как устроено обучение."]] }
];
