/* Ещё тексты для чтения и перевода: рассказы, выжимки книг, статьи и диалоги.
   Формат как у READING (reading.js) плюс поле kind:
   story — рассказ, sum — выжимка книги, art — статья, dlg — диалог.
   Всё написано для приложения; выжимки — краткий пересказ своими словами. */
const STORIES = [
/* ---------- Рассказы ---------- */
{ id: "st1", kind: "story", lvl: "A1", title: "The red umbrella", pairs: [
  ["Anna has a red umbrella.", "У Анны есть красный зонт."],
  ["It is old, but she loves it.", "Он старый, но она его любит."],
  ["One day she leaves it on the bus.", "Однажды она оставляет его в автобусе."],
  ["She is very sad.", "Ей очень грустно."],
  ["The next morning it is raining.", "На следующее утро идёт дождь."],
  ["Anna waits at the bus stop with no umbrella.", "Анна ждёт на остановке без зонта."],
  ["A man stands next to her.", "Рядом с ней стоит мужчина."],
  ["He has a red umbrella in his hand.", "В руке у него красный зонт."],
  ["\"Is this your umbrella?\" he asks.", "«Это ваш зонт?» — спрашивает он."],
  ["\"I found it on the bus yesterday.\"", "«Я нашёл его вчера в автобусе»."],
  ["Anna smiles. \"Yes! Thank you!\"", "Анна улыбается: «Да! Спасибо!»"],
  ["They walk to work together under the red umbrella.", "Они идут на работу вместе под красным зонтом."]] },
{ id: "st2", kind: "story", lvl: "A1", title: "A cat called Monday", pairs: [
  ["We have a cat. His name is Monday.", "У нас есть кот. Его зовут Понедельник."],
  ["We found him on a Monday, so that is his name.", "Мы нашли его в понедельник, поэтому его так зовут."],
  ["He is black and white and very fat.", "Он чёрно-белый и очень толстый."],
  ["Monday sleeps all day.", "Понедельник спит весь день."],
  ["At night he wants to play.", "Ночью он хочет играть."],
  ["He jumps on my bed at three o'clock.", "В три часа он прыгает ко мне на кровать."],
  ["He sits on my face and says \"meow\".", "Он садится мне на лицо и говорит «мяу»."],
  ["I am always tired in the morning.", "Утром я всегда уставший."],
  ["My friends ask, \"Why do you look so bad?\"", "Друзья спрашивают: «Почему ты так плохо выглядишь?»"],
  ["I say, \"Every day is Monday in my house.\"", "Я отвечаю: «В моём доме каждый день — понедельник»."]] },
{ id: "st3", kind: "story", lvl: "A2", title: "The wrong train", pairs: [
  ["Last summer I went to visit my aunt in a small town.", "Прошлым летом я поехал в гости к тёте в маленький город."],
  ["I was tired, so I got on the train without checking the board.", "Я устал, поэтому сел в поезд, не посмотрев на табло."],
  ["I fell asleep almost immediately.", "Я почти сразу уснул."],
  ["When I woke up, the sea was outside the window.", "Когда я проснулся, за окном было море."],
  ["There is no sea near my aunt's town.", "Рядом с тётиным городом нет моря."],
  ["I was on the wrong train, three hundred kilometres from home.", "Я ехал не на том поезде, в трёхстах километрах от дома."],
  ["I called my aunt and told her everything.", "Я позвонил тёте и всё рассказал."],
  ["She laughed and said, \"Well, enjoy the beach!\"", "Она рассмеялась и сказала: «Ну что ж, наслаждайся пляжем!»"],
  ["So I did. I swam, ate fresh fish and watched the sunset.", "Так я и сделал: поплавал, поел свежей рыбы и посмотрел на закат."],
  ["The next day I took the right train.", "На следующий день я сел на правильный поезд."],
  ["Now, every summer, I take the wrong train on purpose.", "Теперь каждое лето я специально сажусь не на тот поезд."]] },
{ id: "st4", kind: "story", lvl: "A2", title: "Grandpa's phone", pairs: [
  ["For his eightieth birthday we gave Grandpa a smartphone.", "На восьмидесятилетие мы подарили дедушке смартфон."],
  ["He looked at it as if it were a dangerous animal.", "Он смотрел на него, как на опасного зверя."],
  ["\"I don't need it,\" he said. \"I have a phone at home.\"", "«Мне он не нужен, — сказал он. — У меня дома есть телефон»."],
  ["My little sister decided to teach him.", "Моя младшая сестра решила его научить."],
  ["Every evening they sat together on the sofa.", "Каждый вечер они сидели вместе на диване."],
  ["First he learned to answer calls, then to send photos.", "Сначала он научился отвечать на звонки, потом — отправлять фото."],
  ["After a month he found videos about fishing.", "Через месяц он нашёл видео про рыбалку."],
  ["After two months he started his own channel.", "Через два месяца он завёл собственный канал."],
  ["Now he has more followers than all of us.", "Теперь у него больше подписчиков, чем у всех нас."],
  ["Yesterday he called me and said, \"Can't talk now, I'm live!\"", "Вчера он позвонил мне и сказал: «Не могу говорить, я в прямом эфире!»"]] },
{ id: "st5", kind: "story", lvl: "A2", title: "The interview", pairs: [
  ["Mark had a job interview at nine o'clock.", "У Марка было собеседование в девять часов."],
  ["He left home early, but the metro stopped between two stations.", "Он вышел из дома рано, но метро остановилось между станциями."],
  ["He waited for forty minutes.", "Он ждал сорок минут."],
  ["When he finally arrived, it was ten o'clock.", "Когда он наконец приехал, было десять."],
  ["In the lift he met an angry man with a coffee.", "В лифте он встретил сердитого мужчину с кофе."],
  ["\"Bad morning?\" Mark asked.", "«Тяжёлое утро?» — спросил Марк."],
  ["\"Terrible,\" said the man. \"The metro stopped, I'm late for an interview.\"", "«Ужасное, — ответил тот. — Метро встало, я опаздываю на собеседование»."],
  ["\"Me too!\" Mark laughed.", "«Я тоже!» — рассмеялся Марк."],
  ["They talked about football until the doors opened.", "Они говорили о футболе, пока не открылись двери."],
  ["Then the man went into the office and sat behind the big desk.", "Потом мужчина вошёл в кабинет и сел за большой стол."],
  ["He was the boss. Mark got the job.", "Это был начальник. Марк получил работу."]] },
{ id: "st6", kind: "story", lvl: "B1", title: "The last letter", pairs: [
  ["When my grandmother died, we found a box of letters under her bed.", "Когда бабушка умерла, мы нашли под её кроватью коробку писем."],
  ["They were all from a man called Peter, and they were written in English.", "Все они были от человека по имени Питер и написаны по-английски."],
  ["Nobody in our family knew that she could speak English.", "Никто в нашей семье не знал, что она говорит по-английски."],
  ["The letters began in 1962 and ended suddenly in 1965.", "Письма начинались в 1962 году и внезапно обрывались в 1965-м."],
  ["Peter wrote about London, about books, and about missing her.", "Питер писал о Лондоне, о книгах и о том, как скучает по ней."],
  ["In the last letter he asked her to come to England.", "В последнем письме он просил её приехать в Англию."],
  ["She never went. A year later she married my grandfather.", "Она так и не поехала. Через год она вышла замуж за моего дедушку."],
  ["I decided to find out what had happened to Peter.", "Я решил узнать, что случилось с Питером."],
  ["After months of searching, I found his daughter online.", "После месяцев поисков я нашёл в интернете его дочь."],
  ["She told me that her father had kept one photo on his desk all his life.", "Она рассказала, что её отец всю жизнь держал на столе одну фотографию."],
  ["It was a photo of a young woman with my grandmother's smile.", "Это было фото молодой женщины с улыбкой моей бабушки."]] },
{ id: "st7", kind: "story", lvl: "B1", title: "Ten thousand steps", pairs: [
  ["My doctor told me I had to walk ten thousand steps a day.", "Врач сказал, что мне нужно проходить десять тысяч шагов в день."],
  ["At first it seemed impossible — I usually walked about two thousand.", "Сначала это казалось невозможным — обычно я проходил около двух тысяч."],
  ["So I started getting off the bus one stop early.", "Поэтому я начал выходить из автобуса на остановку раньше."],
  ["Then I stopped using the lift at work.", "Потом перестал пользоваться лифтом на работе."],
  ["I began to notice things I had never seen before: an old bakery, a tiny park, a street musician.", "Я начал замечать то, чего никогда не видел: старую пекарню, крошечный парк, уличного музыканта."],
  ["The musician played the same song every morning, and I started to look forward to it.", "Музыкант каждое утро играл одну и ту же песню, и я стал ждать этого."],
  ["After a month, I was sleeping better and my back stopped hurting.", "Через месяц я стал лучше спать, и спина перестала болеть."],
  ["After three months, I had lost six kilos.", "Через три месяца я похудел на шесть килограммов."],
  ["But the best thing wasn't the weight.", "Но лучшим было не похудение."],
  ["It was that my city, which I thought I knew, had become new again.", "А то, что мой город, который я, казалось, знал, снова стал новым."]] },
{ id: "st8", kind: "story", lvl: "B1", title: "The neighbour's piano", pairs: [
  ["For years, someone in our building played the piano every evening at eight.", "Много лет кто-то в нашем доме играл на пианино каждый вечер в восемь."],
  ["Nobody knew who it was, and nobody complained, because the music was beautiful.", "Никто не знал, кто это, и никто не жаловался, потому что музыка была прекрасной."],
  ["One evening the music didn't start.", "Однажды вечером музыка не зазвучала."],
  ["It didn't start the next evening either, or the one after that.", "Не зазвучала она и на следующий вечер, и через день."],
  ["We realised how much we had been waiting for it.", "Мы поняли, как сильно её ждали."],
  ["A few of us went from door to door to find the pianist.", "Несколько из нас пошли по квартирам искать пианиста."],
  ["On the fifth floor, an old man opened the door with his arm in plaster.", "На пятом этаже дверь открыл старик с рукой в гипсе."],
  ["He had fallen and broken his wrist.", "Он упал и сломал запястье."],
  ["He was surprised that anyone had even noticed the music.", "Он удивился, что кто-то вообще замечал музыку."],
  ["Since then, we take turns bringing him dinner.", "С тех пор мы по очереди приносим ему ужин."],
  ["And last week, for the first time in two months, the piano played again.", "А на прошлой неделе впервые за два месяца пианино снова заиграло."]] },
{ id: "st9", kind: "story", lvl: "B2", title: "The algorithm", pairs: [
  ["Lena worked for a company that wrote algorithms to predict what people wanted to buy.", "Лена работала в компании, которая писала алгоритмы, предсказывающие, что люди хотят купить."],
  ["She was proud of how accurate they had become.", "Она гордилась тем, насколько точными они стали."],
  ["One morning her phone showed her an advert for a pregnancy test.", "Однажды утром телефон показал ей рекламу теста на беременность."],
  ["She laughed it off, until she realised she was three days late.", "Она отмахнулась, пока не поняла, что задержка уже три дня."],
  ["The test was positive.", "Тест оказался положительным."],
  ["She sat on the bathroom floor, wondering how a machine had known before she did.", "Она сидела на полу ванной и думала, как машина узнала об этом раньше неё."],
  ["It had probably noticed small changes: what she searched for, when she slept, what she ordered.", "Вероятно, она заметила мелкие изменения: что Лена искала, когда спала, что заказывала."],
  ["For the first time, the work she was so proud of felt slightly frightening.", "Впервые работа, которой она так гордилась, показалась ей немного пугающей."],
  ["That afternoon she proposed a new rule at work: some predictions should never be shown.", "В тот же день она предложила на работе новое правило: некоторые прогнозы нельзя показывать никогда."],
  ["Her boss said it would cost money.", "Начальник сказал, что это будет стоить денег."],
  ["\"So does losing people's trust,\" she replied.", "«Потеря доверия людей — тоже», — ответила она."]] },
{ id: "st10", kind: "story", lvl: "B2", title: "Second chance", pairs: [
  ["At forty-five, Oleg lost his job at the factory where he had worked for twenty years.", "В сорок пять Олег потерял работу на заводе, где проработал двадцать лет."],
  ["Everyone told him it was too late to start again.", "Все говорили ему, что начинать заново слишком поздно."],
  ["He spent a month on the sofa, feeling sorry for himself.", "Месяц он пролежал на диване, жалея себя."],
  ["Then his daughter asked him to fix her bike, and he realised he had missed working with his hands.", "Потом дочь попросила починить ей велосипед, и он понял, как скучал по работе руками."],
  ["He fixed the neighbours' bikes, then their friends' bikes.", "Он починил велосипеды соседям, потом их друзьям."],
  ["Within a year, he had rented a small garage and hired an assistant.", "Через год он арендовал небольшой гараж и нанял помощника."],
  ["The money was unpredictable at first, and there were months when he doubted everything.", "Поначалу доход был непредсказуемым, и бывали месяцы, когда он сомневался во всём."],
  ["But he had never looked forward to Mondays before.", "Но раньше он никогда не ждал понедельников с радостью."],
  ["Now, when people ask him for advice, he always says the same thing:", "Теперь, когда у него просят совета, он всегда говорит одно и то же:"],
  ["\"Losing my job was the worst thing that happened to me — and the best.\"", "«Потеря работы — худшее, что со мной случилось, и лучшее»."]] },
/* ---------- Выжимки книг ---------- */
{ id: "sm1", kind: "sum", lvl: "A2", title: "«Маленький принц» — коротко", src: "Антуан де Сент-Экзюпери", pairs: [
  ["A pilot crashes his plane in the desert.", "Лётчик терпит крушение в пустыне."],
  ["There he meets a little prince from a very small planet.", "Там он встречает маленького принца с очень маленькой планеты."],
  ["The prince left his planet because of a proud rose that he loved.", "Принц покинул свою планету из-за гордой розы, которую любил."],
  ["On his journey he visits other planets with strange adults.", "В пути он посещает другие планеты со странными взрослыми."],
  ["A king wants to give orders, a businessman counts stars all day.", "Король хочет отдавать приказы, делец целыми днями считает звёзды."],
  ["On Earth, the prince meets a fox.", "На Земле принц встречает Лиса."],
  ["The fox asks the prince to tame him and become his friend.", "Лис просит принца приручить его и стать его другом."],
  ["The fox tells him a secret: you can only see well with your heart.", "Лис открывает ему секрет: зорко одно лишь сердце."],
  ["The prince understands that his rose is special because he cares for her.", "Принц понимает, что его роза особенная, потому что он о ней заботится."],
  ["Main idea: we are responsible for those we love.", "Главная мысль: мы в ответе за тех, кого любим."]] },
{ id: "sm2", kind: "sum", lvl: "A2", title: "«Старик и море» — коротко", src: "Эрнест Хемингуэй", pairs: [
  ["Santiago is an old fisherman in Cuba.", "Сантьяго — старый рыбак на Кубе."],
  ["He has not caught a fish for eighty-four days.", "Он не ловил рыбы восемьдесят четыре дня."],
  ["One morning he goes far out to sea alone.", "Однажды утром он один уходит далеко в море."],
  ["A huge fish takes his hook.", "Огромная рыба хватает его крючок."],
  ["For three days the old man fights with the fish.", "Три дня старик борется с рыбой."],
  ["His hands bleed, but he does not give up.", "Его руки кровоточат, но он не сдаётся."],
  ["Finally he kills the fish and ties it to his boat.", "Наконец он убивает рыбу и привязывает её к лодке."],
  ["On the way home, sharks eat almost all of it.", "По дороге домой акулы съедают почти всю рыбу."],
  ["He comes back with only the skeleton.", "Он возвращается лишь со скелетом."],
  ["Main idea: a person can be destroyed but not defeated.", "Главная мысль: человека можно уничтожить, но нельзя победить."]] },
{ id: "sm3", kind: "sum", lvl: "A2", title: "«Ромео и Джульетта» — коротко", src: "Уильям Шекспир", pairs: [
  ["Two rich families in Verona hate each other.", "Две богатые семьи в Вероне ненавидят друг друга."],
  ["Romeo is from one family, and Juliet is from the other.", "Ромео из одной семьи, а Джульетта — из другой."],
  ["They meet at a party and fall in love at first sight.", "Они встречаются на празднике и влюбляются с первого взгляда."],
  ["The next day they marry in secret.", "На следующий день они тайно венчаются."],
  ["Romeo kills Juliet's cousin in a fight and has to leave the city.", "Ромео убивает в драке брата Джульетты и вынужден покинуть город."],
  ["Juliet drinks a potion to look dead, so she can escape.", "Джульетта пьёт зелье, чтобы казаться мёртвой и сбежать."],
  ["Romeo doesn't know the plan and thinks she is really dead.", "Ромео не знает о плане и думает, что она действительно умерла."],
  ["He drinks poison next to her.", "Он выпивает яд рядом с ней."],
  ["Juliet wakes up, sees him and kills herself too.", "Джульетта просыпается, видит его и тоже убивает себя."],
  ["Only then do the two families stop fighting.", "Только тогда две семьи прекращают вражду."]] },
{ id: "sm4", kind: "sum", lvl: "B1", title: "«Алхимик» — коротко", src: "Пауло Коэльо", pairs: [
  ["Santiago, a young shepherd in Spain, keeps having the same dream about treasure in Egypt.", "Сантьяго, молодой пастух из Испании, видит один и тот же сон о сокровище в Египте."],
  ["An old king tells him to follow his \"Personal Legend\" — his true purpose.", "Старый царь советует ему следовать своей «Своей Судьбе» — истинному предназначению."],
  ["He sells his sheep and travels to Africa, where he is robbed on the first day.", "Он продаёт овец и отправляется в Африку, где его грабят в первый же день."],
  ["He works for a year in a crystal shop and earns his money back.", "Год он работает в лавке хрусталя и возвращает свои деньги."],
  ["He crosses the desert, falls in love and meets an alchemist.", "Он пересекает пустыню, влюбляется и встречает алхимика."],
  ["The alchemist teaches him to listen to his heart.", "Алхимик учит его слушать своё сердце."],
  ["When he finally reaches the pyramids, he discovers the treasure was back home all along.", "Добравшись до пирамид, он узнаёт, что сокровище всё время было дома."],
  ["But without the journey, he would never have found it — or himself.", "Но без путешествия он бы никогда его не нашёл — как и самого себя."],
  ["Main idea: when you really want something, the whole world helps you get it.", "Главная мысль: когда очень чего-то хочешь, вся Вселенная помогает тебе."]] },
{ id: "sm5", kind: "sum", lvl: "B1", title: "«Атомные привычки» — коротко", src: "Джеймс Клир", pairs: [
  ["Small habits, repeated every day, lead to big results.", "Маленькие привычки, повторяемые каждый день, ведут к большим результатам."],
  ["If you get one percent better every day, you'll be almost forty times better in a year.", "Если становиться лучше на один процент в день, через год будешь почти в сорок раз лучше."],
  ["Don't focus on goals; focus on systems — the things you do daily.", "Сосредоточься не на целях, а на системе — том, что делаешь ежедневно."],
  ["To build a good habit, make it obvious, attractive, easy and satisfying.", "Чтобы выработать хорошую привычку, сделай её заметной, привлекательной, лёгкой и приятной."],
  ["For example, put your English book on your pillow so you see it every night.", "Например, положи учебник английского на подушку, чтобы видеть его каждый вечер."],
  ["Start with a habit so small you can't say no: one page, two minutes.", "Начни с привычки настолько маленькой, что невозможно отказаться: одна страница, две минуты."],
  ["To break a bad habit, do the opposite: make it invisible, unattractive, hard and unsatisfying.", "Чтобы избавиться от плохой привычки, сделай наоборот: незаметной, непривлекательной, трудной и неприятной."],
  ["Never miss twice: one missed day is an accident, two is the start of a new habit.", "Не пропускай дважды: один пропуск — случайность, два — начало новой привычки."],
  ["The real goal is to change your identity: not \"I want to learn English\" but \"I am a person who studies every day\".", "Настоящая цель — изменить представление о себе: не «хочу выучить английский», а «я человек, который занимается каждый день»."]] },
{ id: "sm6", kind: "sum", lvl: "B1", title: "«Преступление и наказание» — коротко", src: "Фёдор Достоевский", pairs: [
  ["Raskolnikov is a poor former student in St Petersburg.", "Раскольников — бедный бывший студент в Петербурге."],
  ["He believes that great people have the right to break the law for a higher purpose.", "Он верит, что великие люди имеют право нарушать закон ради высшей цели."],
  ["To test his theory, he kills an old pawnbroker woman.", "Чтобы проверить свою теорию, он убивает старуху-процентщицу."],
  ["After the murder he becomes ill with fear and guilt.", "После убийства он заболевает от страха и чувства вины."],
  ["A clever detective, Porfiry, suspects him but has no proof.", "Умный следователь Порфирий подозревает его, но доказательств нет."],
  ["Raskolnikov meets Sonya, a poor girl with a deep faith.", "Раскольников встречает Соню — бедную девушку с глубокой верой."],
  ["She convinces him to confess.", "Она убеждает его признаться."],
  ["He is sent to prison in Siberia, and Sonya follows him.", "Его отправляют на каторгу в Сибирь, и Соня едет за ним."],
  ["There, slowly, he begins to change.", "Там он медленно начинает меняться."],
  ["Main idea: no theory can justify taking a human life.", "Главная мысль: никакая теория не оправдывает убийство человека."]] },
{ id: "sm7", kind: "sum", lvl: "B1", title: "«1984» — коротко", src: "Джордж Оруэлл", pairs: [
  ["Winston Smith lives in a country controlled by the Party and its leader, Big Brother.", "Уинстон Смит живёт в стране, которой управляет Партия и её вождь — Старший Брат."],
  ["Screens watch people everywhere, even at home.", "Экраны следят за людьми повсюду, даже дома."],
  ["Winston's job is to change old newspapers so that the Party is always right.", "Работа Уинстона — переписывать старые газеты, чтобы Партия всегда оказывалась права."],
  ["The Party even creates a new language, Newspeak, to make free thinking impossible.", "Партия даже создаёт новый язык — новояз, чтобы свободная мысль стала невозможной."],
  ["Winston secretly falls in love with Julia, which is a crime.", "Уинстон тайно влюбляется в Джулию, а это преступление."],
  ["They are caught and taken to the Ministry of Love.", "Их ловят и отправляют в Министерство любви."],
  ["There Winston is tortured until he betrays Julia.", "Там Уинстона пытают, пока он не предаёт Джулию."],
  ["At the end, he truly believes that two plus two is five, and he loves Big Brother.", "В конце он искренне верит, что дважды два — пять, и любит Старшего Брата."],
  ["Main idea: who controls the past and the language controls people's minds.", "Главная мысль: кто управляет прошлым и языком, тот управляет умами людей."]] },
{ id: "sm8", kind: "sum", lvl: "B1", title: "«7 навыков высокоэффективных людей» — коротко", src: "Стивен Кови", pairs: [
  ["1. Be proactive: you can't control what happens, but you can control how you react.", "1. Будь проактивным: ты не управляешь событиями, но управляешь своей реакцией."],
  ["2. Begin with the end in mind: know what you want before you start.", "2. Начинай, представляя конечную цель: знай, чего хочешь, прежде чем начать."],
  ["3. Put first things first: do the important things before the urgent ones.", "3. Сначала главное: делай важное раньше срочного."],
  ["4. Think win-win: look for solutions that are good for everyone.", "4. Думай в духе «выиграл — выиграл»: ищи решения, выгодные всем."],
  ["5. Seek first to understand, then to be understood: listen before you speak.", "5. Сначала стремись понять, потом — быть понятым: слушай, прежде чем говорить."],
  ["6. Synergize: a team can do more than its members alone.", "6. Синергия: команда способна на большее, чем каждый по отдельности."],
  ["7. Sharpen the saw: take care of your body, mind and relationships.", "7. Затачивай пилу: заботься о теле, уме и отношениях."],
  ["The first three habits are about controlling yourself.", "Первые три навыка — об умении управлять собой."],
  ["The next three are about working with other people.", "Следующие три — о работе с другими людьми."],
  ["The last one keeps all the others alive.", "Последний поддерживает все остальные."]] },
{ id: "sm9", kind: "sum", lvl: "B2", title: "«Sapiens» — коротко", src: "Юваль Ной Харари", pairs: [
  ["Seventy thousand years ago, Homo sapiens was just one of several human species.", "Семьдесят тысяч лет назад Homo sapiens был лишь одним из нескольких видов людей."],
  ["What made us special was the ability to believe in shared stories.", "Нас выделила способность верить в общие истории."],
  ["Gods, nations, money and companies exist only because millions of people believe in them.", "Боги, нации, деньги и компании существуют лишь потому, что в них верят миллионы людей."],
  ["These stories allowed strangers to cooperate in huge numbers.", "Эти истории позволили незнакомцам сотрудничать в огромных количествах."],
  ["The agricultural revolution gave us more food but, for most people, a harder life.", "Аграрная революция дала больше еды, но для большинства — более тяжёлую жизнь."],
  ["Harari calls it \"history's biggest fraud\": we domesticated wheat, but wheat also domesticated us.", "Харари называет её «величайшим обманом в истории»: мы приручили пшеницу, но и она приручила нас."],
  ["Money, empires and religions slowly united humanity into one global system.", "Деньги, империи и религии постепенно объединили человечество в единую глобальную систему."],
  ["The scientific revolution began when people admitted their own ignorance.", "Научная революция началась, когда люди признали собственное невежество."],
  ["Today we have enormous power, yet we are not much happier than our ancestors.", "Сегодня у нас огромная власть, но мы ненамного счастливее предков."],
  ["The final question: what do we want to want?", "Последний вопрос: чего мы хотим хотеть?"]] },
{ id: "sm10", kind: "sum", lvl: "B2", title: "«Думай медленно… решай быстро» — коротко", src: "Даниэль Канеман", pairs: [
  ["Our mind works with two systems.", "Наш разум работает с помощью двух систем."],
  ["System 1 is fast, automatic and emotional: it recognises faces and reacts to danger.", "Система 1 быстрая, автоматическая и эмоциональная: она узнаёт лица и реагирует на опасность."],
  ["System 2 is slow, careful and lazy: it solves maths problems and makes plans.", "Система 2 медленная, вдумчивая и ленивая: она решает задачи и строит планы."],
  ["Most of the time, System 1 is in charge, and that leads to predictable mistakes.", "Большую часть времени главная — Система 1, и это ведёт к предсказуемым ошибкам."],
  ["For example, we judge how likely something is by how easily examples come to mind.", "Например, мы судим о вероятности события по тому, насколько легко вспоминаются примеры."],
  ["That's why many people fear planes more than cars, although cars are far more dangerous.", "Поэтому многие боятся самолётов больше, чем машин, хотя машины гораздо опаснее."],
  ["We also hate losing more than we enjoy winning — this is called loss aversion.", "А ещё проигрыш огорчает нас сильнее, чем радует выигрыш, — это называется неприятием потерь."],
  ["And the first number we hear, even a random one, influences our estimates — the anchoring effect.", "И первое услышанное число, даже случайное, влияет на наши оценки — эффект якоря."],
  ["Practical lesson: for important decisions, slow down and let System 2 check the answer.", "Практический вывод: в важных решениях притормози и дай Системе 2 проверить ответ."]] },
/* ---------- Статьи ---------- */
{ id: "ar1", kind: "art", lvl: "A2", title: "Why we need sleep", pairs: [
  ["Most adults need seven to nine hours of sleep.", "Большинству взрослых нужно семь–девять часов сна."],
  ["While we sleep, the brain does important work.", "Пока мы спим, мозг выполняет важную работу."],
  ["It saves new memories and cleans itself.", "Он сохраняет новые воспоминания и очищает себя."],
  ["That's why you remember new words better after a good night's sleep.", "Поэтому после хорошего сна лучше запоминаешь новые слова."],
  ["People who sleep badly get ill more often.", "Люди, которые плохо спят, чаще болеют."],
  ["They also eat more and feel more stressed.", "А ещё они больше едят и сильнее испытывают стресс."],
  ["To sleep better, go to bed at the same time every day.", "Чтобы лучше спать, ложись в одно и то же время каждый день."],
  ["Don't drink coffee after lunch.", "Не пей кофе после обеда."],
  ["And put your phone away an hour before bed.", "И откладывай телефон за час до сна."]] },
{ id: "ar2", kind: "art", lvl: "A2", title: "Bees", pairs: [
  ["Bees are small, but they are very important.", "Пчёлы маленькие, но очень важные."],
  ["They carry pollen from flower to flower.", "Они переносят пыльцу с цветка на цветок."],
  ["Without them, many fruits and vegetables could not grow.", "Без них многие фрукты и овощи не смогли бы расти."],
  ["About one third of our food depends on bees.", "Около трети нашей еды зависит от пчёл."],
  ["A bee visits up to five thousand flowers a day.", "Пчела посещает до пяти тысяч цветков в день."],
  ["Bees also \"dance\" to tell other bees where to find food.", "Пчёлы ещё и «танцуют», чтобы показать другим, где найти еду."],
  ["Sadly, the number of bees is falling.", "К сожалению, пчёл становится меньше."],
  ["Chemicals and the loss of wild flowers are the main reasons.", "Главные причины — химикаты и исчезновение диких цветов."],
  ["You can help: plant flowers on your balcony or in your garden.", "Ты можешь помочь: посади цветы на балконе или в саду."]] },
{ id: "ar3", kind: "art", lvl: "B1", title: "How to learn a language as an adult", pairs: [
  ["Many adults believe they are too old to learn a new language.", "Многие взрослые считают, что они слишком стары для нового языка."],
  ["In fact, adults often learn faster than children in the first months.", "На самом деле в первые месяцы взрослые часто учатся быстрее детей."],
  ["The difference is that children get thousands of hours of practice.", "Разница в том, что у детей тысячи часов практики."],
  ["So the secret is not age, but time and regularity.", "Так что секрет не в возрасте, а во времени и регулярности."],
  ["Twenty minutes every day is better than three hours once a week.", "Двадцать минут каждый день лучше, чем три часа раз в неделю."],
  ["Learn the most common words first: two thousand words cover most of everyday speech.", "Сначала учи самые частые слова: две тысячи слов покрывают большую часть обычной речи."],
  ["Listen to things that are interesting and only a little difficult for you.", "Слушай то, что интересно и лишь чуть сложнее твоего уровня."],
  ["Speak from the very beginning, even if you make mistakes.", "Говори с самого начала, даже с ошибками."],
  ["Mistakes are not a sign of failure; they are a sign that you are learning.", "Ошибки — не признак неудачи, а признак того, что ты учишься."]] },
{ id: "ar4", kind: "art", lvl: "B1", title: "Social media and happiness", pairs: [
  ["The average person spends more than two hours a day on social media.", "В среднем человек проводит в соцсетях больше двух часов в день."],
  ["These apps are designed to keep us scrolling.", "Эти приложения созданы, чтобы мы продолжали листать."],
  ["Every like gives the brain a small dose of pleasure.", "Каждый лайк даёт мозгу маленькую дозу удовольствия."],
  ["But studies show that heavy users often feel more lonely and anxious.", "Но исследования показывают, что активные пользователи часто чувствуют себя более одинокими и тревожными."],
  ["One reason is comparison: we see other people's best moments and compare them with our ordinary lives.", "Одна из причин — сравнение: мы видим лучшие моменты других и сравниваем их со своей обычной жизнью."],
  ["In one experiment, people who reduced social media to thirty minutes a day felt happier after three weeks.", "В одном эксперименте люди, сократившие соцсети до тридцати минут в день, через три недели почувствовали себя счастливее."],
  ["You don't have to delete your accounts.", "Не обязательно удалять аккаунты."],
  ["Try turning off notifications and keeping your phone out of the bedroom.", "Попробуй отключить уведомления и не держать телефон в спальне."],
  ["Use social media to stay in touch with friends, not to watch strangers.", "Используй соцсети, чтобы общаться с друзьями, а не наблюдать за незнакомцами."]] },
{ id: "ar5", kind: "art", lvl: "B1", title: "Is walking the best exercise?", pairs: [
  ["Walking is free, easy and you can do it almost anywhere.", "Ходьба бесплатна, проста, и ею можно заниматься почти где угодно."],
  ["Thirty minutes of brisk walking a day reduces the risk of heart disease.", "Тридцать минут быстрой ходьбы в день снижают риск болезней сердца."],
  ["It also improves your mood and helps you sleep.", "Она также улучшает настроение и помогает спать."],
  ["Many famous thinkers, like Darwin and Nietzsche, did their best thinking on long walks.", "Многие великие мыслители, например Дарвин и Ницше, лучше всего думали на долгих прогулках."],
  ["Scientists have found that walking increases creativity by up to sixty percent.", "Учёные выяснили, что ходьба повышает творческие способности до шестидесяти процентов."],
  ["You don't need to count ten thousand steps; even seven thousand bring most of the benefits.", "Не обязательно считать десять тысяч шагов: даже семь тысяч дают большую часть пользы."],
  ["Tip: listen to an English podcast while you walk.", "Совет: слушай английский подкаст во время прогулки."],
  ["You'll train your body and your ears at the same time.", "Ты будешь тренировать тело и слух одновременно."]] },
{ id: "ar6", kind: "art", lvl: "B2", title: "The power of boredom", pairs: [
  ["We rarely allow ourselves to be bored anymore: a phone is always within reach.", "Мы почти не позволяем себе скучать: телефон всегда под рукой."],
  ["Yet psychologists argue that boredom plays a useful role.", "Однако психологи утверждают, что скука полезна."],
  ["When the mind has nothing to focus on, it starts to wander.", "Когда уму не на чем сосредоточиться, он начинает блуждать."],
  ["This \"default mode\" is when we make unexpected connections and come up with new ideas.", "В этом «режиме по умолчанию» мы находим неожиданные связи и придумываем новое."],
  ["In one study, people who did a dull task first were more creative afterwards.", "В одном исследовании люди, сначала выполнявшие скучное задание, потом проявляли больше креативности."],
  ["Boredom is also a signal that something in our life needs to change.", "Скука — ещё и сигнал, что в жизни что-то нужно изменить."],
  ["If we constantly silence it with entertainment, we may never hear that message.", "Если постоянно заглушать её развлечениями, мы можем так и не услышать этот сигнал."],
  ["So next time you're waiting in a queue, try leaving your phone in your pocket.", "Поэтому в следующий раз, стоя в очереди, попробуй не доставать телефон."],
  ["You might be surprised by where your thoughts take you.", "Возможно, тебя удивит, куда заведут мысли."]] },
{ id: "ar7", kind: "art", lvl: "B2", title: "Why we procrastinate", pairs: [
  ["Procrastination is not a problem of laziness or poor time management.", "Прокрастинация — это не лень и не плохое планирование времени."],
  ["According to researchers, it is a problem of managing emotions.", "По мнению исследователей, это проблема управления эмоциями."],
  ["We delay tasks that make us feel anxious, bored or insecure.", "Мы откладываем дела, которые вызывают тревогу, скуку или неуверенность."],
  ["Checking social media gives us instant relief, so the brain learns to repeat it.", "Соцсети дают мгновенное облегчение, и мозг учится повторять это."],
  ["Ironically, the relief is short, and the guilt that follows makes the task feel even worse.", "Ирония в том, что облегчение недолгое, а последующее чувство вины делает задачу ещё неприятнее."],
  ["One effective strategy is to make the first step ridiculously small: \"just open the document\".", "Одна действенная стратегия — сделать первый шаг до смешного маленьким: «просто открой документ»."],
  ["Another is self-compassion: people who forgive themselves for procrastinating do it less next time.", "Другая — сочувствие к себе: те, кто прощает себе прокрастинацию, в следующий раз откладывают меньше."],
  ["Finally, remove temptations: put your phone in another room.", "И наконец, убери соблазны: положи телефон в другую комнату."],
  ["The task rarely turns out to be as unpleasant as we imagined.", "Задача редко оказывается такой неприятной, как мы себе представляли."]] },
{ id: "ar8", kind: "art", lvl: "B2", title: "Life on Mars?", pairs: [
  ["For centuries people have wondered whether there is life on Mars.", "Веками люди задаются вопросом, есть ли жизнь на Марсе."],
  ["Today we know that the planet is cold, dry and exposed to dangerous radiation.", "Сегодня мы знаем, что планета холодная, сухая и подвержена опасной радиации."],
  ["However, billions of years ago it had rivers, lakes and possibly an ocean.", "Однако миллиарды лет назад там были реки, озёра и, возможно, океан."],
  ["Rovers have found ancient riverbeds and minerals that only form in water.", "Марсоходы нашли древние русла рек и минералы, образующиеся только в воде."],
  ["If life ever existed there, it was probably microscopic.", "Если жизнь там и была, то, вероятно, микроскопическая."],
  ["Scientists are now collecting rock samples that may one day be brought back to Earth.", "Сейчас учёные собирают образцы пород, которые однажды могут доставить на Землю."],
  ["Finding even a single fossil microbe would change our understanding of the universe.", "Находка даже одного окаменевшего микроба изменила бы наше представление о Вселенной."],
  ["It would mean that life is not a rare accident, but something that happens wherever conditions allow.", "Это означало бы, что жизнь — не редкая случайность, а то, что возникает везде, где позволяют условия."]] },
/* ---------- Диалоги ---------- */
{ id: "dl1", kind: "dlg", lvl: "A2", title: "At the doctor's", pairs: [
  ["— Good morning. What seems to be the problem?", "— Доброе утро. На что жалуетесь?"],
  ["— I've had a sore throat and a headache for three days.", "— У меня три дня болит горло и голова."],
  ["— Do you have a temperature?", "— Температура есть?"],
  ["— Yes, about thirty-eight last night.", "— Да, вчера вечером было около тридцати восьми."],
  ["— Let me have a look. Open your mouth, please.", "— Давайте посмотрю. Откройте рот, пожалуйста."],
  ["— It's a throat infection. Nothing serious.", "— Это инфекция горла. Ничего серьёзного."],
  ["— Do I need antibiotics?", "— Мне нужны антибиотики?"],
  ["— No, just rest, drink a lot of water and take this twice a day.", "— Нет, просто отдыхайте, пейте много воды и принимайте это два раза в день."],
  ["— Can I go to work?", "— Можно мне на работу?"],
  ["— Better stay at home for two or three days.", "— Лучше побудьте дома два-три дня."]] },
{ id: "dl2", kind: "dlg", lvl: "A2", title: "Booking a table", pairs: [
  ["— Hello, Bella Italia. How can I help you?", "— Здравствуйте, «Белла Италия». Чем могу помочь?"],
  ["— Hi, I'd like to book a table for Saturday evening.", "— Здравствуйте, я хотел бы забронировать столик на субботу вечером."],
  ["— Of course. For how many people?", "— Конечно. На сколько человек?"],
  ["— Four, please. At about eight o'clock.", "— На четверых, пожалуйста. Примерно на восемь."],
  ["— I'm sorry, we're full at eight. Is half past eight OK?", "— Извините, на восемь всё занято. Половина девятого подойдёт?"],
  ["— Yes, that's fine.", "— Да, подходит."],
  ["— Can I have your name, please?", "— Как вас зовут?"],
  ["— It's Ivanov. I-V-A-N-O-V.", "— Иванов. И-В-А-Н-О-В."],
  ["— Thank you. Would you like a table by the window?", "— Спасибо. Хотите столик у окна?"],
  ["— That would be lovely. Thank you!", "— Было бы чудесно. Спасибо!"]] },
{ id: "dl3", kind: "dlg", lvl: "B1", title: "Renting a flat", pairs: [
  ["— Hi, I'm calling about the flat on Green Street. Is it still available?", "— Здравствуйте, я звоню насчёт квартиры на Грин-стрит. Она ещё свободна?"],
  ["— Yes, it is. Would you like to come and see it?", "— Да. Хотите приехать посмотреть?"],
  ["— Yes, please. But first, can I ask a few questions?", "— Да, но сначала можно пару вопросов?"],
  ["— Sure, go ahead.", "— Конечно, спрашивайте."],
  ["— Are the bills included in the rent?", "— Коммунальные услуги включены в аренду?"],
  ["— Water and heating are included, but electricity isn't.", "— Вода и отопление включены, а электричество — нет."],
  ["— How much is the deposit?", "— Какой залог?"],
  ["— One month's rent, and you'll get it back when you leave.", "— Месячная плата; вернём, когда будете съезжать."],
  ["— Are pets allowed? I have a small cat.", "— С животными можно? У меня маленькая кошка."],
  ["— A cat is fine, as long as she doesn't damage the furniture.", "— Кошка — пожалуйста, если не будет портить мебель."],
  ["— Great. Could I come tomorrow after work, around six?", "— Отлично. Можно я приеду завтра после работы, около шести?"],
  ["— Six is perfect. See you then.", "— Шесть — идеально. До встречи."]] },
{ id: "dl4", kind: "dlg", lvl: "B1", title: "A complaint in a hotel", pairs: [
  ["— Excuse me, I'm in room 214. I'm afraid there's a problem.", "— Извините, я в номере 214. Боюсь, у нас проблема."],
  ["— I'm sorry to hear that. What's wrong?", "— Мне жаль это слышать. Что случилось?"],
  ["— The air conditioning isn't working, and the room is really hot.", "— Не работает кондиционер, а в номере очень жарко."],
  ["— I do apologise. I'll send someone to fix it right away.", "— Приношу извинения. Сейчас же пришлю мастера."],
  ["— Also, there's a lot of noise from the street. I couldn't sleep last night.", "— И ещё очень шумно с улицы. Я ночью не мог уснуть."],
  ["— Would you like to move to a quieter room at the back?", "— Хотите переехать в более тихий номер с окнами во двор?"],
  ["— Yes, that would be great, if it's possible.", "— Да, было бы здорово, если возможно."],
  ["— Of course. And breakfast tomorrow is on us, to make up for the trouble.", "— Конечно. И завтрак завтра за наш счёт — в качестве компенсации."],
  ["— That's very kind of you. Thank you.", "— Очень любезно с вашей стороны. Спасибо."]] },
{ id: "dl5", kind: "dlg", lvl: "B1", title: "Small talk at work", pairs: [
  ["— Morning! How was your weekend?", "— Доброе утро! Как выходные?"],
  ["— Not bad, thanks. We finally went to that new Georgian restaurant.", "— Неплохо, спасибо. Мы наконец сходили в тот новый грузинский ресторан."],
  ["— Oh, I've heard about it. Is it any good?", "— О, я слышал о нём. Хороший?"],
  ["— It's amazing. You have to try the khachapuri.", "— Потрясающий. Обязательно попробуй хачапури."],
  ["— I'll keep that in mind. What about you?", "— Учту. А у тебя как?"],
  ["— Pretty quiet. I mostly stayed in and watched a series.", "— Довольно спокойно. В основном сидел дома и смотрел сериал."],
  ["— Anything worth watching?", "— Что-нибудь стоящее?"],
  ["— Yes, a detective show — I can't remember the name, I'll send you the link.", "— Да, детектив — не помню названия, скину ссылку."],
  ["— Thanks. Anyway, are you ready for the meeting at ten?", "— Спасибо. Кстати, готов к совещанию в десять?"],
  ["— Not really. I need another coffee first!", "— Не особо. Сначала мне нужен ещё кофе!"]] },
{ id: "dl6", kind: "dlg", lvl: "B2", title: "Job interview", pairs: [
  ["— So, tell me a little about yourself.", "— Итак, расскажите немного о себе."],
  ["— I've been working in sales for five years, mostly with international clients.", "— Я пять лет работаю в продажах, в основном с иностранными клиентами."],
  ["— Why are you interested in this position?", "— Почему вас интересует эта должность?"],
  ["— I'm looking for a role where I can take on more responsibility and lead a team.", "— Я ищу должность, где смогу взять на себя больше ответственности и руководить командой."],
  ["— What would you say is your greatest weakness?", "— Какой ваш самый большой недостаток?"],
  ["— I used to find it hard to delegate, but I've learned that trusting the team gets better results.", "— Раньше мне было трудно делегировать, но я понял, что доверие команде даёт лучший результат."],
  ["— Can you give me an example of a difficult situation you handled?", "— Приведите пример трудной ситуации, с которой вы справились."],
  ["— Last year we nearly lost our biggest client because of a delivery delay.", "— В прошлом году мы чуть не потеряли крупнейшего клиента из-за задержки поставки."],
  ["— I flew to meet them in person, explained the problem honestly and offered a discount.", "— Я полетел на встречу лично, честно объяснил проблему и предложил скидку."],
  ["— They not only stayed, they doubled their order.", "— Они не только остались, но и удвоили заказ."],
  ["— Impressive. Do you have any questions for us?", "— Впечатляет. У вас есть к нам вопросы?"],
  ["— Yes — what does success look like in this role after the first six months?", "— Да: каким должен быть успех на этой должности через первые полгода?"]] }
];
if (typeof READING !== "undefined") READING.push(...STORIES);
// у прежних текстов «Чтения» вида не было: истории — рассказы, статьи — статьи
if (typeof READING !== "undefined") READING.forEach(t => { if (!t.kind) t.kind = ["r10", "r12", "r13", "r14"].includes(t.id) ? "art" : "story"; });
