/* Темы словаря для марафона слов. Каждое слово — в одной теме.
   Разговорные фразы, фразовые глаголы и свои слова получают тему сами. */
const TOPICS = [
  { id: "people", emoji: "👨‍👩‍👧", name: "Люди и семья", words: "people|man|woman|child|family|friend|mother|father|brother|sister|name|guest|neighbour|colleague|boss|customer|crowd|relationship|birthday|life|world" },
  { id: "home", emoji: "🏠", name: "Дом и быт", words: "home|house|room|door|table|kitchen|flat|rent|clothes|phone|wash|clean|dirty|comfortable|wear|own|noise|quiet|loud|sleep|dog" },
  { id: "food", emoji: "🍔", name: "Еда", words: "food|water|bread|coffee|breakfast|lunch|dinner|meal|eat|drink|cook|hungry" },
  { id: "travel", emoji: "✈️", name: "Город и путешествия", words: "city|street|shop|car|bus|train|ticket|holiday|trip|journey|travel|abroad|country|village|area|view|arrive|drive|walk|swim|foreign|place|way|weather|season" },
  { id: "work", emoji: "💼", name: "Работа и деньги", words: "work|job|money|pay|buy|sell|price|expensive|cheap|bill|salary|earn|spend|save|company|meeting|career|income|debt|task|workload|afford|waste|rich|poor|busy|borrow|lend|order|apply|manage|tool" },
  { id: "health", emoji: "🩺", name: "Тело и здоровье", words: "health|healthy|ill|pain|hurt|hospital|tired|exhausted|stress|strong|weak|survive|hand|head|face|eye" },
  { id: "feel", emoji: "😊", name: "Чувства и характер", words: "love|like|hate|happy|sad|angry|afraid|worry|nervous|enjoy|smile|laugh|lucky|kind|friendly|polite|rude|lazy|funny|serious|honest|generous|grateful|guilty|proud|upset|disappointed|embarrassed|curious|confident|confidence|patient|independent|reliable|responsible|careful|boring|interesting|strange|famous|popular|attitude|behaviour|behave|miss|hope|dream" },
  { id: "fun", emoji: "🎬", name: "Досуг", words: "music|film|picture|play|watch" },
  { id: "study", emoji: "🎓", name: "Учёба и язык", words: "school|book|word|language|learn|read|write|speak|understand|question|answer|repeat|explain|describe|mistake|skill|ability|information|research|evidence|source|mean|news|rule|law|pass|fail|improve" },
  { id: "talk", emoji: "🗣", name: "Общение", words: "talk|tell|call|ask|agree|argue|complain|promise|invite|offer|suggest|recommend|mention|admit|deny|persuade|convince|blame|encourage|remind|opinion|advice|share|join|meet|send|receive|feedback|compromise|acknowledge|emphasise|exaggerate|imply|interpret|justify" },
  { id: "mind", emoji: "🧠", name: "Мышление и решения", words: "think|know|feel|decide|decision|choose|choice|prefer|plan|remember|forget|notice|realise|recognise|consider|expect|suppose|assume|predict|anticipate|compare|difference|reason|problem|solve|idea|sure|likely|obvious|aware|awareness|assumption|bias|insight|perspective|determine|evaluate|assess|regret|depend" },
  { id: "verbs", emoji: "🏃", name: "Главные глаголы", words: "be|have|do|go|get|make|see|come|want|look|use|find|give|try|need|leave|put|keep|let|begin|start|help|show|hear|run|live|bring|happen|sit|stand|lose|open|close|wait|carry|change|check|fall|fill|finish|follow|grow|pull|push|reach|steal|throw|win|return|protect|prepare|allow|create|produce|provide|include|replace|require|avoid|prevent|reduce|increase|develop|gain|appear|involve|achieve|succeed|support|deal with|rely on|cope with|adapt|contribute|emerge|enhance|ensure|implement|indicate|maintain|neglect|obtain|overcome|overlook|pursue|reinforce|resolve|restrict|reveal|seek|sustain|undermine|withdraw|influence|refuse|deserve|attempt|effort" },
  { id: "time", emoji: "⏰", name: "Время и частота", words: "time|year|day|week|morning|evening|night|today|tomorrow|yesterday|now|always|never|often|sometimes|usually|already|still|again|early|later|ago|once|finally|suddenly|eventually|gradually|immediately|recently|rarely|future|previous|next|last|first|long|quickly|slowly|mostly" },
  { id: "adj", emoji: "📏", name: "Описания и качества", words: "good|bad|new|old|big|small|little|great|right|wrong|different|same|young|important|easy|difficult|simple|hot|cold|beautiful|ready|free|safe|dangerous|danger|quality|value|essential|available|convenient|flexible|familiar|reasonable|adequate|ambiguous|comprehensive|considerable|crucial|deliberate|inevitable|plausible|profound|reluctant|subtle|sufficient|thorough|tremendous|vague|vulnerable|worthwhile" },
  { id: "link", emoji: "🔗", name: "Связки для речи", words: "very|really|also|maybe|together|because|but|if|when|where|why|how|what|who|which|with|without|about|before|after|between|here|there|almost|enough|especially|instead|probably|actually|apparently|certainly|completely|hardly|otherwise|therefore|though|unless|whereas|although|despite|however|whether|arguably|consequently|furthermore|nevertheless|presumably|ultimately|merely" },
  { id: "goals", emoji: "🎯", name: "Цели и проблемы", words: "goal|purpose|success|result|outcome|risk|threat|challenge|opportunity|advantage|disadvantage|benefit|drawback|consequence|implication|condition|issue|lack|shortage|amount|approach|strategy|priority|setback|breakthrough|burden|commitment|concern|incentive|responsibility|habit|environment|experience" },
  { id: "chunks", emoji: "💬", name: "Разговорные фразы", kind: "ch" },
  { id: "phrasal", emoji: "🧩", name: "Фразовые глаголы", kind: "pv" },
  { id: "own", emoji: "✍️", name: "Мои слова", kind: "own" }
];
